import type { LandingPage } from "./types";

const technikraum = "/optimized/elektro-zaehlerschrank-wechselrichter-f85da1e7f3.webp";

export const electricalPages: LandingPage[] = [
  {
    slug: "elektriker-mindelheim",
    regional: true, category: "elektro", adGroup: "Elektriker Region",
    intent: "Regionalen Elektriker für ein konkretes Elektroprojekt finden",
    title: "Elektriker in Mindelheim & Umgebung | ALAB",
    description: "Elektrofachbetrieb in Mindelheim: Installation, Umbau, Verteilungen, PV und Wallbox. Ingenieurplanung und Umsetzung aus einer Hand. Projekt anfragen.",
    eyebrow: "Elektrotechnik · Mindelheim & Umgebung",
    h1: "Elektriker & Elektrofachbetrieb in Mindelheim und Umgebung",
    intro: "Sie planen einen Umbau, neue Stromkreise oder den Anschluss Ihrer Energietechnik? ALAB prüft den Bestand, plant die passende Lösung und übernimmt die Elektroinstallation.",
    cta: "Elektroprojekt anfragen", benefits: ["Ingenieurbüro & Elektrofachbetrieb", "Planung und Umsetzung aus einer Hand", "Persönlicher Kontakt in Mindelheim"],
    heroImage: technikraum, heroAlt: "Geöffneter Zählerschrank neben Wechselrichter und Stromspeicher in einem Technikraum", heroCaption: "Zählerschrank, Wechselrichter und Speicher im Technikraum",
    focusTitle: "Ein Elektroprojekt beginnt mit Ihrem Vorhaben.",
    focusIntro: "Zusätzliche Steckdosen, eine neue Verteilung oder der Anschluss einer Wärmepumpe: Entscheidend ist, dass die Lösung zum Gebäude und zur vorhandenen Installation passt.",
    focusItems: [
      { title: "Umbauen & erweitern", text: "Wir klären, welche Stromkreise und Anschlüsse Sie benötigen und wie sie sich in den Bestand einbinden lassen." },
      { title: "Modernisieren & prüfen", text: "Verteilungen, Schutzmaßnahmen und Anschlussleistung werden gemeinsam betrachtet. So entsteht ein nachvollziehbarer Maßnahmenumfang." },
      { title: "Energietechnik anschließen", text: "PV, Wallbox und Wärmepumpe benötigen passende Leitungen und Absicherungen. Wir planen die elektrische Einbindung mit." },
    ],
    servicesTitle: "Elektroinstallation in Mindelheim: unsere Leistungen",
    services: [
      { title: "Installation & Umbau", text: "Leitungen, Anschlüsse, Steckdosen und Beleuchtung für Ihre Nutzung planen und installieren." },
      { title: "Zähler & Verteilungen", text: "Vorhandene Anlagen beurteilen und erforderliche Erweiterungen oder Modernisierungen abstimmen." },
      { title: "PV & Wallbox", text: "Elektrische Einbindung, Schutzkonzept und Anschluss mit dem Anlagenkonzept zusammenführen." },
      { title: "Wärmepumpenversorgung", text: "Leistungsbedarf, Stromversorgung und erforderliche Anpassungen am Zählerschrank prüfen." },
      { title: "Prüfung & Dokumentation", text: "Die ausgeführten Arbeiten prüfen und die zugehörigen Unterlagen für die Übergabe erstellen." },
      { title: "Abstimmung vor Ort", text: "Leitungswege und Arbeitsbereiche besprechen und den Ablauf auf Ihr Gebäude abstimmen." },
    ],
    steps: [
      { title: "Vorhaben schildern", text: "Teilen Sie uns mit, was Sie ändern möchten und wo Ihr Gebäude liegt." },
      { title: "Bestand klären", text: "Wir besprechen die Anforderungen und stimmen eine technische Aufnahme ab." },
      { title: "Angebot erhalten", text: "Sie erhalten einen auf den vereinbarten Umfang abgestimmten Vorschlag." },
      { title: "Umsetzen & prüfen", text: "Wir installieren, prüfen und übergeben die ausgeführten Arbeiten." },
    ],
    faqs: [
      { question: "Welche Elektroarbeiten kann ich anfragen?", answer: "Zum Beispiel Installationen bei Umbauten, zusätzliche Stromkreise, Verteilungen und Zähleranlagen sowie die elektrische Einbindung von PV, Wallbox und Wärmepumpe. Beschreiben Sie Ihr Vorhaben kurz, damit wir den Umfang einordnen können." },
      { question: "Arbeitet ALAB auch außerhalb von Mindelheim?", answer: "Unser Standort ist Mindelheim. Projekte im Unterallgäu und im Allgäu stimmen wir abhängig von Ort und Umfang individuell ab. Ihre Postleitzahl hilft uns bei der ersten Einordnung." },
      { question: "Können Teile einer älteren Installation erhalten bleiben?", answer: "Das hängt vom Zustand, den vorhandenen Schutzmaßnahmen und der geplanten Nutzung ab. Wir beurteilen den Bestand, bevor wir notwendige Änderungen empfehlen." },
      { question: "Kann ich Elektroarbeiten mit einer PV-Anlage verbinden?", answer: "Ja, bei der Planung lassen sich PV-Anschluss, Verteilung, Zählerschrank und mögliche Erweiterungen gemeinsam betrachten. Dadurch werden die Schnittstellen früh geklärt." },
      { question: "Welche Angaben benötigt ALAB für ein Angebot?", answer: "Hilfreich sind die Postleitzahl, die Gebäudeart und eine kurze Beschreibung der gewünschten Arbeiten. Fotos oder Pläne können wir anschließend gezielt mit Ihnen abstimmen." },
      { question: "Bietet diese Anfrage einen Elektro-Notdienst?", answer: "Das Formular ist für planbare Projekte vorgesehen. Eine sofortige Bearbeitung oder Notdienstbereitschaft wird darüber nicht zugesagt." },
    ],
    formTitle: "Was möchten Sie elektrisch verändern?", formIntro: "Nennen Sie uns Ihr Vorhaben und den Projektort. Wir klären mit Ihnen den nächsten sinnvollen Schritt.", projectType: "Elektroinstallation",
    qualifier: { label: "Worum geht es?", options: ["Umbau / Erweiterung", "Verteilung / Zählerschrank", "PV / Wallbox / Wärmepumpe", "Prüfung / Modernisierung", "Noch offen"] },
    related: ["elektroinstallation-neubau-sanierung", "zaehlerschrank-modernisieren"],
  },
  {
    slug: "elektromeister-mindelheim",
    regional: true, category: "elektro", adGroup: "Elektriker_Elektromeister_Regional",
    intent: "Fachliche Planung und Ausführung komplexerer elektrotechnischer Arbeiten",
    title: "Elektromeister & Elektrofachbetrieb Mindelheim | ALAB",
    description: "Elektromeister gesucht? ALAB in Mindelheim verbindet Ingenieurplanung mit Elektroinstallation: Zähleranlagen, Verteilungen, Umbauten und Energietechnik.",
    eyebrow: "Planung & Ausführung · Elektrotechnik",
    h1: "Elektromeister & Elektrofachbetrieb für Mindelheim und Umgebung",
    intro: "Für elektrotechnische Umbauten zählt das Gesamtkonzept. ALAB verbindet Ingenieurplanung und Elektrofachbetrieb – von der Bestandsaufnahme bis zur geprüften Ausführung.",
    cta: "Elektroplanung anfragen", benefits: ["Technische Planung im eigenen Haus", "Abgestimmte Zähler- und Schutzkonzepte", "Ausführung mit Dokumentation"],
    heroImage: technikraum, heroAlt: "Geöffneter Zählerschrank neben Wechselrichter und Stromspeicher in einem Technikraum", heroCaption: "Zählerschrank, Wechselrichter und Speicher im Technikraum",
    focusTitle: "Komplexe Elektrotechnik braucht einen gemeinsamen Plan.",
    focusIntro: "Wenn neue Verbraucher auf bestehende Anlagen treffen, reicht es nicht, einzelne Komponenten auszutauschen. Wir betrachten Leistung, Verteilung und künftige Nutzung zusammen.",
    focusItems: [
      { title: "Anforderungen erfassen", text: "Bestehende Anschlüsse, neue Verbraucher und Erweiterungswünsche bilden die Grundlage der Planung." },
      { title: "Schnittstellen klären", text: "Zählerkonzept, Netzbetreiber und Anforderungen von PV, Wallbox oder Wärmepumpe werden aufeinander abgestimmt." },
      { title: "Ausführung nachvollziehbar machen", text: "Ein klarer Leistungsumfang, abgestimmte Arbeitsschritte und Prüfunterlagen schaffen eine belastbare Übergabe." },
    ],
    servicesTitle: "Elektrofachbetrieb mit Blick auf das Gesamtsystem",
    services: [
      { title: "Technische Planung", text: "Lasten, Stromkreise und Schutzmaßnahmen passend zum Vorhaben auslegen." },
      { title: "Zähleranlagen", text: "Messkonzept und erforderliche Anpassungen mit den Anschlussanforderungen abgleichen." },
      { title: "Haupt- & Unterverteilungen", text: "Neue Stromkreise integrieren und Platz sowie Leistungsreserven berücksichtigen." },
      { title: "Umbauten & Erweiterungen", text: "Arbeitsabschnitte, Abschaltungen und Anschlüsse im bestehenden Gebäude abstimmen." },
      { title: "Energietechnik", text: "PV, Speicher, Ladeinfrastruktur und Wärmepumpe elektrisch zusammenführen." },
      { title: "Prüfung & Übergabe", text: "Ausgeführte Installation prüfen und die vereinbarten Dokumente zusammenstellen." },
    ],
    steps: [
      { title: "Aufgabe definieren", text: "Sie beschreiben Nutzung, Umfang und vorhandene Unterlagen." },
      { title: "Technik aufnehmen", text: "Wir erfassen die relevanten Schnittstellen und den Zustand der Anlage." },
      { title: "Konzept abstimmen", text: "Leistungsumfang, Ausführung und Ablauf werden konkret vereinbart." },
      { title: "Installieren & übergeben", text: "Umsetzung, Prüfung und Dokumentation schließen das Projekt ab." },
    ],
    faqs: [
      { question: "Wann ist eine technische Planung besonders sinnvoll?", answer: "Zum Beispiel bei mehreren neuen Großverbrauchern, umfangreichen Umbauten oder Änderungen an Zähleranlage und Verteilung. Die Planung klärt, welche Teile zusammenpassen und welche Arbeiten erforderlich sind." },
      { question: "Übernimmt ALAB auch die Ausführung?", answer: "ALAB verbindet Ingenieurbüro und eigenen Elektrofachbetrieb. Planung und vereinbarte Elektroarbeiten können deshalb aus einer Hand erfolgen." },
      { question: "Wie werden Anforderungen des Netzbetreibers berücksichtigt?", answer: "Wir prüfen, welche Vorgaben und Abstimmungen für Ihren Anschluss relevant sind. Erforderliche Anmeldungen und Zuständigkeiten werden im Projektumfang festgelegt." },
      { question: "Kann eine bestehende Verteilung erweitert werden?", answer: "Das wird anhand von Zustand, Platz, Anschlussleistung und Schutzkonzept geprüft. Ein vollständiger Austausch ist keine pauschale Voraussetzung jeder Erweiterung." },
      { question: "Lassen sich spätere Verbraucher vorbereiten?", answer: "Ja, beispielsweise durch abgestimmte Leitungswege, Platzreserven und ein geeignetes Anlagenkonzept. Welche Vorbereitungen sinnvoll sind, hängt von Ihren konkreten Plänen ab." },
      { question: "Welche Unterlagen helfen bei der Erstprüfung?", answer: "Vorhandene Stromlaufpläne, Angaben zum Anschluss, Fotos der Anlage und Daten der geplanten Verbraucher sind hilfreich. Fehlende Unterlagen besprechen wir bei der Bestandsaufnahme." },
    ],
    formTitle: "Lassen Sie uns die technische Aufgabe klären.", formIntro: "Ob Erweiterung oder neues Anlagenkonzept: Beschreiben Sie den Anlass. Wir besprechen die passende Vorgehensweise.", projectType: "Elektroplanung / komplexer Umbau",
    qualifier: { label: "Schwerpunkt Ihres Projekts", options: ["Zähleranlage", "Verteilung / Umbau", "Energietechnik integrieren", "Neues Anlagenkonzept", "Noch offen"] },
    related: ["zaehlerschrank-modernisieren", "elektriker-mindelheim"],
  },
  {
    slug: "elektroinstallation-neubau-sanierung", category: "elektro", adGroup: "Elektroinstallation Neubau & Sanierung",
    intent: "Elektroinstallation für Neubau oder Bestandsmodernisierung planen lassen",
    title: "Elektroinstallation Neubau & Sanierung | ALAB",
    description: "Elektroinstallation für Neubau und Sanierung: Stromkreise, Licht, Netzwerk, Zählerschrank und Vorbereitung für PV, Wallbox und Wärmepumpe – geplant und umgesetzt von ALAB.",
    eyebrow: "Ihr Gebäude · Ihre Elektroinstallation",
    h1: "Elektroinstallation für Neubau & Sanierung",
    intro: "Eine gute Elektroinstallation passt zu Ihrem Alltag und zu Ihrer Energietechnik. Wir planen Anschlüsse, Stromkreise und Verteilungen und setzen die abgestimmte Lösung um.",
    cta: "Elektroinstallation anfragen", benefits: ["Raumweise abgestimmte Planung", "Neubau und Bestand individuell betrachtet", "PV, Wallbox und Wärmepumpe mitgedacht"],
    heroImage: technikraum, heroAlt: "Geöffneter Zählerschrank neben Wechselrichter und Stromspeicher in einem Technikraum", heroCaption: "Zählerschrank, Wechselrichter und Speicher im Technikraum",
    focusTitle: "Neubau oder Sanierung: zwei Ausgangspunkte, ein durchdachtes Ergebnis.",
    focusIntro: "Wählen Sie den Weg, der zu Ihrem Gebäude passt. Beide beginnen mit der Frage, wie Sie Ihre Räume heute und später nutzen möchten.",
    focusItems: [
      { title: "Neubau", text: "Vom Grundriss aus planen wir Steckdosen, Licht, Netzwerk und Stromkreise. Leitungswege und Reserven lassen sich früh mit den übrigen Gewerken abstimmen." },
      { title: "Sanierung / Altbau", text: "Zuerst prüfen wir die vorhandene Installation. Danach legen wir fest, was erhalten bleibt, was ergänzt wird und wie sich die Arbeiten in Bauabschnitte aufteilen lassen." },
    ],
    servicesTitle: "Was wir bei Ihrer Elektroinstallation einplanen",
    services: [
      { title: "Steckdosen & Stromkreise", text: "Anschlüsse nach Raumnutzung und Leistungsbedarf statt nach einem pauschalen Raster." },
      { title: "Beleuchtung", text: "Lichtauslässe, Schaltstellen und gewünschte Steuerungen früh im Grundriss abstimmen." },
      { title: "Netzwerk", text: "Datenanschlüsse und Leitungswege passend zu Arbeitsplatz, Wohnen und Technik vorsehen." },
      { title: "Zähler & Unterverteilungen", text: "Verteilung, Schutzmaßnahmen und Platzbedarf als zusammenhängendes System planen." },
      { title: "Energie & Mobilität", text: "PV-Vorbereitung, Wallbox und Wärmepumpenversorgung in das Konzept aufnehmen." },
      { title: "Schutz & Prüfung", text: "Schutzkonzept einschließlich erforderlichem Überspannungsschutz planen und die Ausführung prüfen." },
    ],
    steps: [
      { title: "Gebäude zuordnen", text: "Neubau oder Sanierung, Grundriss und Projektstand mitteilen." },
      { title: "Nutzung besprechen", text: "Raum für Raum Anschlüsse und technische Wünsche erfassen." },
      { title: "Planung abstimmen", text: "Umfang, Schnittstellen und Angebot gemeinsam festlegen." },
      { title: "Bauablauf begleiten", text: "Die Installation in abgestimmten Schritten ausführen und prüfen." },
    ],
    faqs: [
      { question: "Wann sollte die Elektroplanung im Neubau beginnen?", answer: "Sobald Grundrisse und Nutzung ausreichend konkret sind. Früh geplante Anschlüsse, Technikflächen und Leitungswege erleichtern die Abstimmung mit anderen Gewerken." },
      { question: "Muss bei einer Sanierung die gesamte Elektrik erneuert werden?", answer: "Das lässt sich erst nach einer Bestandsaufnahme beurteilen. Zustand, Schutzmaßnahmen und die geplante Nutzung entscheiden darüber, welche Teile erhalten oder erneuert werden sollten." },
      { question: "Kann eine Sanierung in Abschnitten erfolgen?", answer: "Das ist je nach Anlage und Bauablauf möglich. Wir klären, wie Arbeitsbereiche, Abschaltungen und die Versorgung der weiter genutzten Räume organisiert werden können." },
      { question: "Was sollte ich für eine spätere Wallbox oder PV-Anlage vorbereiten?", answer: "Leitungswege, mögliche Technikflächen und Platz in der Verteilung lassen sich früh berücksichtigen. Die konkreten Voraussetzungen werden anhand des Gebäudes und der vorgesehenen Systeme geplant." },
      { question: "Plant ALAB auch Netzwerk und Beleuchtung?", answer: "Datenanschlüsse, Lichtauslässe und Schaltstellen können in die Elektroplanung aufgenommen werden. Umfang und gewünschte Funktionen stimmen wir mit Ihnen ab." },
      { question: "Welche Angaben benötigen Sie zu Beginn?", answer: "Gebäudeart, Postleitzahl, Projektstand und die Information Neubau oder Sanierung genügen für den Einstieg. Vorhandene Grundrisse und Ausstattungswünsche helfen bei der weiteren Planung." },
    ],
    formTitle: "Planen wir die Elektrik für Ihr Gebäude.", formIntro: "Teilen Sie uns mit, ob Sie neu bauen oder sanieren. Details und Unterlagen klären wir anschließend persönlich.", projectType: "Elektroinstallation Neubau / Sanierung",
    qualifier: { label: "Ihr Vorhaben", options: ["Neubau", "Sanierung / Altbau", "Teilmodernisierung", "Noch in der Orientierung"] },
    related: ["zaehlerschrank-modernisieren", "elektromeister-mindelheim"],
  },
  {
    slug: "zaehlerschrank-modernisieren", category: "elektro", adGroup: "Zählerschrank & Verteilung",
    intent: "Bestehende Zähleranlage oder Sicherungsverteilung prüfen und modernisieren",
    title: "Zählerschrank erneuern & Verteilung modernisieren | ALAB",
    description: "Zählerschrank für PV, Wärmepumpe oder Wallbox prüfen lassen. ALAB plant die notwendige Anpassung von Zähleranlage und Elektroverteilung.",
    eyebrow: "Zähleranlage · Verteilung · Energietechnik",
    h1: "Zählerschrank erneuern & Elektroverteilung modernisieren",
    intro: "Neue PV-Anlage, Wärmepumpe oder Wallbox geplant? Wir prüfen Ihren Zählerschrank und zeigen, welche Anpassungen für Ihr Vorhaben tatsächlich erforderlich sind.",
    cta: "Zähleranlage prüfen lassen", benefits: ["Bestand zuerst fachlich beurteilen", "Anschlussanforderungen berücksichtigen", "Umbau und Inbetriebnahme abstimmen"],
    heroImage: technikraum, heroAlt: "Geöffneter Zählerschrank neben Wechselrichter und Stromspeicher in einem Technikraum", heroCaption: "Zählerschrank, Wechselrichter und Speicher im Technikraum",
    focusTitle: "Muss Ihr Zählerschrank wirklich komplett neu?",
    focusIntro: "Das Alter allein beantwortet diese Frage nicht. Zustand, Aufbau und die Anforderungen der geplanten Erweiterung bestimmen, ob eine Anpassung genügt oder ein Austausch sinnvoll ist.",
    focusItems: [
      { title: "Was ist vorhanden?", text: "Wir erfassen Aufbau, Platzreserven, Schutzmaßnahmen und die vorhandene Anschluss- und Zählersituation." },
      { title: "Was kommt hinzu?", text: "PV, Wärmepumpe und Wallbox stellen unterschiedliche Anforderungen an Leistung, Messung und Steuerung." },
      { title: "Was muss angepasst werden?", text: "Aus Bestand und neuem Anlagenkonzept ergibt sich der notwendige Umfang – einschließlich relevanter Netzbetreibervorgaben." },
    ],
    servicesTitle: "Zählerschrank modernisieren: den gesamten Anschluss betrachten",
    services: [
      { title: "Bestandsaufnahme", text: "Zähleranlage und Verteilungen vor der Festlegung des Umbaus prüfen." },
      { title: "Zähler- & Anschlusskonzept", text: "Messung und technische Anschlussanforderungen für das konkrete Vorhaben abstimmen." },
      { title: "Verteilung & Schutz", text: "Stromkreise, Absicherungen und erforderlichen Überspannungsschutz berücksichtigen." },
      { title: "PV, Wärmepumpe & Wallbox", text: "Neue Verbraucher und Erzeugungsanlagen passend in die elektrische Anlage integrieren." },
      { title: "Umbau koordinieren", text: "Abschaltung, Arbeitsablauf und bei Bedarf einen Zählerwechsel mit den zuständigen Stellen abstimmen." },
      { title: "Prüfen & dokumentieren", text: "Die ausgeführten Arbeiten prüfen und die vereinbarten Unterlagen übergeben." },
    ],
    steps: [
      { title: "Anlass mitteilen", text: "Beschreiben Sie den geplanten Umbau oder neuen Verbraucher." },
      { title: "Zähleranlage prüfen", text: "Wir klären den Bestand und die technischen Anforderungen." },
      { title: "Umfang festlegen", text: "Sie erhalten ein Angebot für die erforderlichen Maßnahmen." },
      { title: "Umbau durchführen", text: "Termin, Versorgungspause und notwendige Abstimmungen werden geplant." },
    ],
    faqs: [
      { question: "Braucht jede PV-Anlage einen neuen Zählerschrank?", answer: "Nein, das lässt sich nicht pauschal sagen. Wir prüfen die bestehende Anlage, die geplante PV-Einbindung und die relevanten technischen Anschlussanforderungen." },
      { question: "Woran unterscheiden sich Zählerschrank und Unterverteilung?", answer: "Der Zählerschrank beherbergt die Zählung und weitere Anschlusskomponenten. Unterverteilungen verteilen die Stromkreise in Gebäudeabschnitten. Bei einer Modernisierung betrachten wir beide entsprechend ihrem Einfluss auf das Vorhaben." },
      { question: "Kann ich einen alten Sicherungskasten erweitern lassen?", answer: "Das hängt unter anderem von Zustand, Platz, Belastbarkeit und Schutzmaßnahmen ab. Nach der Aufnahme lässt sich beurteilen, ob eine Erweiterung oder Erneuerung erforderlich ist." },
      { question: "Wer stimmt einen notwendigen Zählerwechsel ab?", answer: "Ein Zählerwechsel betrifft den zuständigen Messstellenbetreiber. Wir klären im Projekt, welche Abstimmungen und Vorarbeiten erforderlich sind und wer welchen Schritt übernimmt." },
      { question: "Wird der Strom beim Umbau abgeschaltet?", answer: "Für Arbeiten an der Zähleranlage sind in der Regel abgestimmte Abschaltungen nötig. Dauer und Ablauf hängen vom Umbauumfang und den beteiligten Stellen ab und werden vorab besprochen." },
      { question: "Was kostet die Erneuerung des Zählerschranks?", answer: "Der Preis richtet sich nach Bestand, Größe, erforderlichen Schutzkomponenten, Leitungsanpassungen und Anschlusskonzept. Ein belastbares Angebot folgt der technischen Prüfung." },
    ],
    formTitle: "Klären wir, was Ihre Zähleranlage braucht.", formIntro: "Nennen Sie den Anlass der Modernisierung und Ihren Projektort. Die technischen Details besprechen wir gemeinsam.", projectType: "Zählerschrank / Verteilung",
    qualifier: { label: "Anlass der Prüfung", options: ["Photovoltaik", "Wärmepumpe", "Wallbox", "Umbau / alte Verteilung", "Mehrere Erweiterungen"] },
    related: ["elektromeister-mindelheim", "elektroinstallation-neubau-sanierung"],
  },
];
