import type { LandingPage } from "./types";

const kfwSource = {
  title: "KfW: Heizungsförderung für Privatpersonen – Wohngebäude (458), geprüft am 22.09.2026",
  url: "https://www.kfw.de/inlandsfoerderung/Privatpersonen/Bestehende-Immobilie/F%C3%B6rderprodukte/Heizungsf%C3%B6rderung-f%C3%BCr-Privatpersonen-Wohngeb%C3%A4ude-%28458%29/",
};

export const heatpumpPages: LandingPage[] = [
  {
    slug: "waermepumpe-altbau",
    category: "waermepumpe",
    adGroup: "WP Umrüsten & Altbau",
    intent: "Öl- oder Gasheizung im Bestandsgebäude durch eine passend ausgelegte Wärmepumpe ersetzen.",
    title: "Wärmepumpe im Altbau: Heizung umrüsten | ALAB",
    description: "Wärmepumpe im Altbau nachrüsten: ALAB prüft Heizkörper, Heizlast und Elektroinstallation. Planung und Umsetzung in Mindelheim und im Allgäu anfragen.",
    eyebrow: "Heizungstausch · Altbau & Bestand",
    h1: "Wärmepumpe im Altbau – Heizung professionell umrüsten",
    intro: "Raus aus Öl oder Gas: Wir prüfen Ihr Heizsystem, dimensionieren die passende Wärmepumpe und planen Umbau, Warmwasser und Elektroanschluss. Für Ihr Bestandsgebäude in Mindelheim und im Allgäu.",
    cta: "Altbau prüfen lassen",
    benefits: ["Heizkörper und Vorlauftemperatur prüfen", "Heizlast statt pauschaler Gerätegröße", "Planung und Umsetzung aus einer Hand"],
    heroImage: "/optimized/waermepumpe-bosch-7bd7fd7c72.webp",
    heroAlt: "Wärmepumpen-Außeneinheit an einer Hausfassade als Beispiel für einen Heizungstausch",
    heroCaption: "Produktbeispiel · Bosch Wärmepumpe",
    focusTitle: "Passt eine Wärmepumpe zu Ihrem Altbau?",
    focusIntro: "Entscheidend ist das Zusammenspiel aus Wärmebedarf, Heizflächen und Temperatur. Wir klären, was bleiben kann und wo Anpassungen sinnvoll sind.",
    focusItems: [
      { title: "Heizkörper weiter nutzen?", text: "Wir prüfen die vorhandenen Heizflächen und die erforderliche Vorlauftemperatur. Eine Fußbodenheizung ist keine pauschale Voraussetzung." },
      { title: "Welche Leistung braucht das Haus?", text: "Heizlast, Dämmzustand und geplante Sanierungen bestimmen die Auslegung. Der bisherige Verbrauch liefert dazu erste Anhaltspunkte." },
      { title: "Was muss beim Umbau mitgedacht werden?", text: "Warmwasser, Aufstellort, Leitungswege und Zählerschrank gehören zusammen. Diese Punkte berücksichtigen wir vor dem Angebot." },
    ],
    servicesTitle: "Wärmepumpe nachrüsten: Das planen wir mit",
    services: [
      { title: "Bestandsaufnahme & Heizlast", text: "Gebäude, Heizflächen und Verbrauch erfassen; Leistung und Betriebsweise darauf abstimmen." },
      { title: "Heizungstausch & Hydraulik", text: "Rückbau der Altanlage, Einbindung der Wärmepumpe und erforderliche Anpassungen im Heizkreis festlegen." },
      { title: "Warmwasser & Speicher", text: "Speicherbedarf, vorhandene Technik und Platz im Heizraum gemeinsam betrachten." },
      { title: "Elektroanschluss & Zählerschrank", text: "Versorgung, Absicherung und vorhandene Zähleranlage auf den neuen Verbraucher prüfen." },
      { title: "Aufstellung & Montage", text: "Außeneinheit, Fundament, Leitungsführung und Geräuschentwicklung bei der Planung berücksichtigen." },
      { title: "PV & Fördermöglichkeiten", text: "Solarstrom und mögliche Förderung frühzeitig einordnen; technische Umsetzung und zeitlichen Ablauf abstimmen." },
    ],
    steps: [
      { title: "Bestand beschreiben", text: "Sie nennen Gebäude, aktuelle Heizung und den Anlass für den Wechsel." },
      { title: "Eignung prüfen", text: "Wir betrachten Heizflächen, Temperaturbedarf, Aufstellort und Elektroanlage." },
      { title: "Umbau planen", text: "Sie erhalten ein abgestimmtes Konzept mit nachvollziehbarem Leistungsumfang." },
      { title: "Heizung umstellen", text: "Nach Freigabe und geklärtem Förderablauf folgen Umbau, Inbetriebnahme und Einweisung." },
    ],
    faqs: [
      { question: "Funktioniert eine Wärmepumpe auch im unsanierten Altbau?", answer: "Das lässt sich nicht allein am Baujahr entscheiden. Maßgeblich sind Wärmebedarf, Heizflächen und die benötigten Temperaturen. Wir prüfen Ihren Bestand und zeigen, ob die Umrüstung direkt oder mit begleitenden Maßnahmen sinnvoll ist." },
      { question: "Müssen alle Heizkörper durch eine Fußbodenheizung ersetzt werden?", answer: "Nein, nicht grundsätzlich. Entscheidend ist, ob die vorhandenen Heizkörper bei den vorgesehenen Temperaturen genügend Wärme abgeben. Manchmal genügt die Anpassung einzelner Heizflächen. Das klären wir anhand Ihres Gebäudes." },
      { question: "Welche Vorlauftemperatur ist für mein Haus nötig?", answer: "Sie hängt unter anderem von Heizlast, Heizkörpergröße und Außentemperatur ab. Eine niedrige erforderliche Temperatur ist für den Betrieb günstig. Wir betrachten die tatsächlichen Anforderungen, statt mit einem pauschalen Grenzwert zu planen." },
      { question: "Kann die Wärmepumpe auch das Warmwasser übernehmen?", answer: "Ja, die Warmwasserbereitung lässt sich in das Anlagenkonzept einbinden. Personenanzahl, Nutzungsverhalten und vorhandener Speicher bestimmen, welche Lösung zu Ihrem Haushalt und dem verfügbaren Platz passt." },
      { question: "Muss für den Heizungstausch der Zählerschrank erneuert werden?", answer: "Das prüfen wir im Bestand. Eine neue Wärmepumpe bedeutet nicht automatisch einen vollständigen Austausch. Erforderliche Anpassungen ergeben sich aus der vorhandenen Anlage, dem Anschlusskonzept und den technischen Anforderungen." },
      { question: "Kann ich eine Wärmepumpe später mit Photovoltaik verbinden?", answer: "Ja, das lässt sich bereits bei der Auslegung und Elektroplanung berücksichtigen. Wie viel Solarstrom die Wärmepumpe nutzen kann, hängt von Erzeugung, Wärmebedarf und Regelung ab. Auch eine bestehende PV-Anlage beziehen wir ein." },
    ],
    formTitle: "Ist Ihr Altbau bereit für die Wärmepumpe?",
    formIntro: "Nennen Sie uns Ihren Standort und die bisherige Heizung. Gemeinsam klären wir, welche Angaben und Prüfungen als Nächstes sinnvoll sind.",
    projectType: "Wärmepumpe – Altbau / Heizungstausch",
    qualifier: { label: "Womit heizen Sie bisher?", options: ["Gasheizung", "Ölheizung", "Andere Heizung", "Noch unklar"] },
    related: ["waermepumpe-kosten", "waermepumpe-foerderung", "photovoltaik-mit-speicher"],
  },
  {
    slug: "waermepumpe-angebot",
    category: "waermepumpe",
    adGroup: "Wärmepumpe Angebot/Kaufen",
    intent: "Ein konkretes Angebot für eine Wärmepumpe einschließlich Planung, Einbau und Elektroarbeiten erhalten.",
    title: "Wärmepumpe kaufen: Komplettangebot anfragen | ALAB",
    description: "Wärmepumpe kaufen mit Planung, Montage und Elektroarbeiten aus einer Hand. Individuelles Komplettangebot von ALAB für Mindelheim und das Allgäu anfragen.",
    eyebrow: "Ihr Wärmepumpen-Angebot",
    h1: "Wärmepumpe kaufen – individuelles Komplettangebot erhalten",
    intro: "Sie möchten eine Wärmepumpe kaufen und wissen, was der Einbau umfasst? ALAB plant Ihre Anlage inklusive Hydraulik, Warmwasser und Elektroarbeiten – passend zu Ihrem Gebäude im Allgäu.",
    cta: "Wärmepumpen-Angebot anfordern",
    benefits: ["Auf Ihr Gebäude ausgelegt", "Leistungsumfang klar beschrieben", "Planung, Montage und Elektroarbeiten"],
    heroImage: "/optimized/waermepumpe-bosch-7bd7fd7c72.webp",
    heroAlt: "Bosch Wärmepumpe vor einer Hausfassade als Produktbeispiel für ein individuelles Angebot",
    heroCaption: "Produktbeispiel · Bosch Wärmepumpe",
    focusTitle: "Ein Wärmepumpen-Angebot, das den Einbau mitdenkt",
    focusIntro: "Der Gerätepreis allein sagt wenig über Ihr Projekt aus. Wir erfassen die technischen Voraussetzungen und stimmen den gesamten Leistungsumfang mit Ihnen ab.",
    focusItems: [
      { title: "Passend dimensioniert", text: "Gebäude, Heizlast und Warmwasserbedarf bilden die Grundlage für die Geräteauswahl." },
      { title: "Schnittstellen geklärt", text: "Heizkreis, Stromversorgung, Aufstellfläche und Zähleranlage fließen in die Planung ein." },
      { title: "Angebote besser vergleichen", text: "Sie sehen, welche Leistungen enthalten sind, welche Optionen bestehen und welche Voraussetzungen noch zu klären sind." },
    ],
    servicesTitle: "Diese Leistungen kann Ihr Komplettangebot enthalten",
    services: [
      { title: "Planung & Auslegung", text: "Bestandsaufnahme, Heizlast und Auswahl der passenden Wärmepumpe." },
      { title: "Wärmepumpe & Montage", text: "Gerät, Aufstellung, Leitungswege und die vereinbarten Montagearbeiten." },
      { title: "Hydraulische Einbindung", text: "Anschluss an Ihre Heizkreise und erforderliche Anpassungen der Wärmeverteilung." },
      { title: "Warmwasserlösung", text: "Abgestimmtes Speicherkonzept für Haushaltsgröße, Bedarf und vorhandenen Platz." },
      { title: "Elektroinstallation", text: "Versorgung und Absicherung; Anpassungen am Zählerschrank, soweit erforderlich." },
      { title: "Inbetriebnahme & Übergabe", text: "Funktionsprüfung, Einweisung, Dokumentation und erforderliche Abstimmung mit dem Netzbetreiber." },
    ],
    steps: [
      { title: "Angebot anfragen", text: "Wenige Angaben zu Gebäude und Vorhaben reichen für den ersten Kontakt." },
      { title: "Technik prüfen", text: "Wir klären die Ausgangslage und vereinbaren die nötige Bestandsaufnahme." },
      { title: "Angebot besprechen", text: "Sie erhalten ein Anlagenkonzept mit den vereinbarten Leistungen und Optionen." },
      { title: "Projekt umsetzen", text: "Nach Freigabe und Klärung des Förderablaufs folgen Installation und Inbetriebnahme." },
    ],
    faqs: [
      { question: "Welche Angaben brauchen Sie für ein Wärmepumpen-Angebot?", answer: "Zum Start helfen Standort, Gebäudeart und die bisherige Heizung. Für das konkrete Angebot besprechen wir außerdem Wohnfläche, Verbrauch, Heizflächen und Aufstellmöglichkeiten. Vorhandene Pläne und Fotos können die Bestandsaufnahme ergänzen." },
      { question: "Ist der Einbau im Komplettangebot enthalten?", answer: "Der vereinbarte Einbau gehört zum beschriebenen Leistungsumfang. Wir legen fest, welche Montage-, Hydraulik- und Elektroarbeiten enthalten sind. Zusätzliche Optionen und eventuell erforderliche Leistungen werden vor Beauftragung besprochen." },
      { question: "Bekomme ich ein Angebot einschließlich Zählerschrank?", answer: "Wenn Anpassungen erforderlich sind, berücksichtigen wir diese im abgestimmten Angebot. Dafür prüfen wir zuerst Ihre vorhandene Zähleranlage und das geplante Anschlusskonzept. Ein pauschaler Austausch ist nicht bei jedem Projekt notwendig." },
      { question: "Kann ich auch die Demontage meiner alten Heizung anfragen?", answer: "Ja. Geben Sie bei Ihrer Anfrage an, welche Heizung ersetzt werden soll. Wir klären den Rückbau und die damit verbundenen Arbeiten, etwa am Speicher oder an vorhandenen Leitungen, als Teil des Gesamtprojekts." },
      { question: "Wie schnell kann meine Wärmepumpe installiert werden?", answer: "Der Termin hängt vom technischen Umfang, der Verfügbarkeit der Komponenten und den nötigen Abstimmungen ab. Einen realistischen Ablauf besprechen wir, sobald die Voraussetzungen Ihres Projekts geklärt sind." },
      { question: "Bin ich mit der Angebotsanfrage bereits gebunden?", answer: "Nein. Mit dem Formular schildern Sie zunächst Ihr Vorhaben. Die Anfrage ist noch keine Beauftragung. Über das konkrete Angebot und den vereinbarten Leistungsumfang entscheiden Sie nach der technischen Klärung." },
    ],
    formTitle: "Ihr Wärmepumpen-Angebot beginnt hier",
    formIntro: "Teilen Sie uns mit, was Sie vorhaben. Wir klären die nächsten Schritte für ein Angebot, das zu Ihrem Gebäude passt.",
    projectType: "Wärmepumpe – Komplettangebot",
    qualifier: { label: "Wofür möchten Sie ein Angebot?", options: ["Gas- oder Ölheizung ersetzen", "Wärmepumpe im Neubau", "Vorhandene Wärmepumpe ersetzen", "Projekt noch in Planung"] },
    earlyForm: true,
    related: ["waermepumpe-altbau", "waermepumpe-kosten", "waermepumpe-allgaeu"],
  },
  {
    slug: "waermepumpe-allgaeu",
    category: "waermepumpe",
    adGroup: "WP Fachbetrieb Region",
    intent: "Einen regionalen Wärmepumpen-Fachbetrieb mit persönlicher Planung und eigener Umsetzung finden.",
    title: "Wärmepumpen-Fachbetrieb im Allgäu & Mindelheim | ALAB",
    description: "Wärmepumpen von ALAB in Mindelheim: Ingenieurbüro und Elektrofachbetrieb für Planung, Montage und Inbetriebnahme im Unterallgäu und Allgäu.",
    eyebrow: "Mindelheim · Unterallgäu · Allgäu",
    h1: "Wärmepumpen-Fachbetrieb für Mindelheim, Unterallgäu & Allgäu",
    intro: "Ihre Wärmepumpe braucht einen Fachbetrieb, der Gebäude und Elektrotechnik zusammen plant. ALAB verbindet Ingenieurplanung mit eigenen Fachkräften und einem persönlichen Ansprechpartner – von Mindelheim aus für Ihr Projekt im Allgäu.",
    cta: "Wärmepumpen-Projekt besprechen",
    benefits: ["Standort in Mindelheim", "Ingenieurbüro und Elektrofachbetrieb", "Persönliche Begleitung bis zur Übergabe"],
    heroImage: "/optimized/waermepumpe-hochformat-4fc396c70d.webp",
    heroAlt: "Luft-Wasser-Wärmepumpe im Garten vor einem Wohnhaus",
    heroCaption: "Luft-Wasser-Wärmepumpe am Wohnhaus",
    focusTitle: "Ihr Wärmepumpen-Fachbetrieb mit Sitz in Mindelheim",
    focusIntro: "Ein Heizungstausch betrifft mehr als den Heizraum. Bei ALAB laufen Gebäudeplanung, Wärmepumpentechnik und Elektroinstallation in einem abgestimmten Projekt zusammen.",
    focusItems: [
      { title: "Ein konkreter Ansprechpartner", text: "Sie besprechen Ihr Vorhaben mit dem Betrieb, der Planung und Umsetzung organisiert. Offene Punkte klären wir direkt mit Ihnen." },
      { title: "Ihr Gebäude vor Ort verstehen", text: "Heizflächen, Aufstellort und Stromversorgung prüfen wir am tatsächlichen Bestand – als Grundlage für ein passendes Konzept." },
      { title: "Elektrotechnik im eigenen Betrieb", text: "Wärmepumpe, Zählerschrank, PV und Wallbox werden gemeinsam betrachtet. Das vermeidet ungeklärte Schnittstellen in der Planung." },
    ],
    servicesTitle: "Wärmepumpen im Allgäu: Von der Planung bis zum Betrieb",
    services: [
      { title: "Beratung & Vor-Ort-Prüfung", text: "Ausgangslage, Wünsche und technische Möglichkeiten persönlich besprechen." },
      { title: "Ingenieurplanung", text: "Heizlast, Systemauswahl und Einbindung in das Gebäude zusammenführen." },
      { title: "Montage & Elektroarbeiten", text: "Wärmepumpe und elektrische Versorgung im abgestimmten Projekt umsetzen." },
      { title: "Inbetriebnahme & Einweisung", text: "Anlage prüfen, Einstellungen erläutern und die Dokumentation übergeben." },
      { title: "Service abstimmen", text: "Wartungsbedarf und weitere Betreuung passend zur gewählten Anlage besprechen." },
    ],
    steps: [
      { title: "Regional anfragen", text: "Sie nennen den Projektort und Ihre bisherige Heizsituation." },
      { title: "Persönlich kennenlernen", text: "Wir klären Anforderungen und die nächsten Schritte zur Prüfung vor Ort." },
      { title: "Gemeinsam festlegen", text: "Konzept, Leistungsumfang und Ablauf werden vor der Beauftragung besprochen." },
      { title: "Anlage übergeben", text: "Montage, Inbetriebnahme und Einweisung schließen die Umsetzung ab." },
    ],
    faqs: [
      { question: "Wo sitzt ALAB Energiesysteme?", answer: "Unser Standort ist im Kastanienweg 6 in 87719 Mindelheim. Sie erreichen uns unter 08261 7597176 oder über das Anfrageformular. Für ein persönliches Gespräch stimmen wir einen Termin mit Ihnen ab." },
      { question: "Betreuen Sie Wärmepumpen-Projekte im gesamten Allgäu?", answer: "Wir nehmen Anfragen aus Mindelheim, dem Unterallgäu und dem Allgäu entgegen. Nennen Sie uns Ihre Postleitzahl und das Vorhaben. Ob und wie wir Ihr Projekt übernehmen können, klären wir im ersten Kontakt." },
      { question: "Kommt vor dem Angebot jemand zum Gebäude?", answer: "Die nötige Bestandsaufnahme stimmen wir nach dem Erstgespräch ab. Gerade beim Heizungstausch sind Heizraum, Aufstellfläche und Elektroinstallation vor Ort wichtig, um Umfang und technische Voraussetzungen zuverlässig zu erfassen." },
      { question: "Ist ALAB ein Vermittler für Wärmepumpen?", answer: "ALAB ist ein Ingenieurbüro und Elektrofachbetrieb. Wir verbinden technische Planung mit handwerklicher Umsetzung durch eigene Fachkräfte. Den konkreten Leistungsumfang und die Zuständigkeiten stimmen wir für Ihr Projekt ab." },
      { question: "Können Sie Wärmepumpe und Photovoltaik gemeinsam planen?", answer: "Ja. Wir betrachten Wärmeerzeugung und Stromversorgung gemeinsam. Eine vorhandene oder geplante PV-Anlage, ein Speicher und eine Wallbox lassen sich so frühzeitig in das elektrische Gesamtkonzept einordnen." },
      { question: "Wer ist nach der Inbetriebnahme mein Ansprechpartner?", answer: "Wenden Sie sich auch nach der Übergabe an ALAB. Welche Wartungs- und Serviceleistungen für Ihre Anlage sinnvoll sind und vereinbart werden, besprechen wir im Rahmen Ihres Projekts." },
    ],
    formTitle: "Besprechen wir Ihre Wärmepumpe im Allgäu",
    formIntro: "Mit Ihrer Postleitzahl und einer kurzen Beschreibung können wir Ihr Vorhaben regional und technisch einordnen.",
    projectType: "Wärmepumpe – regionaler Fachbetrieb",
    qualifier: { label: "Was planen Sie?", options: ["Heizung im Bestand ersetzen", "Wärmepumpe für einen Neubau", "Wärmepumpe und PV kombinieren", "Zunächst Möglichkeiten besprechen"] },
    related: ["waermepumpe-altbau", "waermepumpe-angebot", "photovoltaik-allgaeu"],
  },
  {
    slug: "waermepumpe-foerderung",
    category: "waermepumpe",
    adGroup: "WP Förderung",
    intent: "Fördermöglichkeiten für einen Heizungstausch einordnen und den technischen Ablauf richtig vorbereiten.",
    title: "Wärmepumpen-Förderung prüfen & Projekt planen | ALAB",
    description: "Wärmepumpen-Förderung für Ihr Vorhaben einordnen: ALAB klärt technische Voraussetzungen und die Planung Ihres Heizungstauschs im Allgäu.",
    eyebrow: "Heizungstausch mit Förderperspektive",
    h1: "Wärmepumpen-Förderung: Förderung prüfen und richtig planen",
    intro: "Sie möchten Ihre Heizung ersetzen und Fördermöglichkeiten berücksichtigen? Wir prüfen gemeinsam, was für Ihr Vorhaben grundsätzlich infrage kommt, und klären die technische Planung Ihrer Wärmepumpe im Allgäu.",
    cta: "Fördermöglichkeiten prüfen lassen",
    benefits: ["Gebäude und Maßnahme zuerst prüfen", "Technische Voraussetzungen klären", "Antrag und Umsetzung richtig einordnen"],
    heroImage: "/optimized/waermepumpe-bosch-7bd7fd7c72.webp",
    heroAlt: "Bosch Wärmepumpe vor einer Hausfassade als Produktbeispiel für einen geplanten Heizungstausch",
    heroCaption: "Produktbeispiel · Bosch Wärmepumpe",
    focusTitle: "Wärmepumpen-Förderung beginnt mit guter Vorbereitung",
    focusIntro: "Die Förderstelle entscheidet über den Zuschuss. Wir schaffen mit Ihnen die technische Grundlage und orientieren uns am aktuellen Förderprogramm – ohne pauschale Zusage.",
    focusItems: [
      { title: "Ihr Vorhaben einordnen", text: "Gebäude, Eigentumssituation und bestehende Heizung helfen, das passende Programm zu finden. Die KfW bietet eine Heizungsförderung für private Wohngebäude." },
      { title: "Technik und Kosten vorbereiten", text: "Für den KfW-Antrag ist eine Bestätigung zum Antrag erforderlich. Sie enthält unter anderem technische Angaben und förderfähige Kosten." },
      { title: "Die Reihenfolge beachten", text: "Beim KfW-Programm 458 muss der Antrag vor den Arbeiten vor Ort gestellt werden. Der erforderliche Vertrag muss eine Förderbedingung enthalten." },
    ],
    servicesTitle: "So unterstützen wir die Planung Ihrer Wärmepumpe",
    services: [
      { title: "Bestandsgebäude erfassen", text: "Heizung, Heizflächen, Verbrauch und geplante Sanierungsschritte zusammen betrachten." },
      { title: "Technisches Konzept entwickeln", text: "Wärmepumpe und Warmwasserlösung passend zum Gebäude auslegen." },
      { title: "Leistungsumfang klären", text: "Heizungstausch, Montage, hydraulische Arbeiten und Elektroinstallation nachvollziehbar beschreiben." },
      { title: "Unterlagen abstimmen", text: "Besprechen, welche technischen Angaben benötigt werden und wer die erforderlichen Nachweise erstellt." },
      { title: "PV gesondert mitdenken", text: "Eine Photovoltaikanlage technisch einbeziehen und ihre Finanzierung getrennt von der Heizungsförderung betrachten." },
    ],
    steps: [
      { title: "Vorhaben schildern", text: "Sie nennen den Gebäudetyp und die Heizung, die ersetzt werden soll." },
      { title: "Planung vorbereiten", text: "Wir klären Technik, Leistungsumfang und benötigte Unterlagen." },
      { title: "Förderablauf klären", text: "Aktuelle Programmbedingungen, Vertragsgestaltung und Antragstellung vor dem Start abstimmen." },
      { title: "Umsetzung planen", text: "Nach geklärtem Förderstatus den Einbau und die Dokumentation abstimmen." },
    ],
    faqs: [
      { question: "Welche Förderung kommt für meine Wärmepumpe infrage?", answer: "Für den Heizungstausch in privaten Wohngebäuden kann das KfW-Programm 458 relevant sein. Ob Ihr Vorhaben die Bedingungen erfüllt, richtet sich nach dem aktuellen Programm und Ihrer Situation. Die offizielle KfW-Seite ist unten verlinkt." },
      { question: "Wann muss ich den Förderantrag stellen?", answer: "Bei KfW 458 muss der Antrag vor Beginn der Arbeiten vor Ort erfolgen. Vorher ist ein Lieferungs- oder Leistungsvertrag mit aufschiebender oder auflösender Bedingung zur Förderzusage erforderlich. Prüfen Sie die aktuellen Vorgaben vor dem Vertragsabschluss." },
      { question: "Kann ALAB mir eine bestimmte Förderhöhe zusagen?", answer: "Nein. Die Förderstelle entscheidet anhand Ihres Antrags und der geltenden Bedingungen. Wir können die technische Planung mit Ihnen vorbereiten. Eine pauschale Förderhöhe oder verbindliche Förderzusage lässt sich daraus nicht ableiten." },
      { question: "Sind Arbeiten an Heizkörpern und Elektroanschluss automatisch förderfähig?", answer: "Nicht jede Projektposition ist automatisch förderfähig. Welche begleitenden Arbeiten berücksichtigt werden können, muss anhand des aktuellen Programms und Ihres Vorhabens geprüft werden. Ein klar gegliedertes Angebot erleichtert die Zuordnung." },
      { question: "Wird eine gleichzeitig installierte PV-Anlage ebenfalls über die Heizungsförderung abgedeckt?", answer: "Gehen Sie nicht davon aus, dass die Heizungsförderung auch Ihre PV-Anlage abdeckt. Wir betrachten beide Anlagen technisch gemeinsam; Förderfähigkeit und Finanzierung müssen für die jeweiligen Maßnahmen gesondert geprüft werden." },
      { question: "Was sollte ich für das erste Gespräch bereithalten?", answer: "Hilfreich sind Angaben zur bestehenden Heizung, zum Gebäude und zu bereits geplanten Arbeiten. Teilen Sie uns außerdem mit, ob schon ein Angebot, ein Vertrag oder ein Förderantrag vorliegt. So lässt sich der nächste Schritt gezielt klären." },
    ],
    formTitle: "Fördermöglichkeiten für Ihr Wärmepumpen-Projekt einordnen",
    formIntro: "Beschreiben Sie Ihre Ausgangslage. Wir klären mit Ihnen die technische Planung und den weiteren Ablauf; über eine Förderung entscheidet die zuständige Stelle.",
    projectType: "Wärmepumpe – Fördermöglichkeiten",
    qualifier: { label: "Wo steht Ihr Vorhaben?", options: ["Erste Orientierung", "Angebot wird vorbereitet", "Förderantrag wird vorbereitet", "Förderzusage liegt vor", "Vertrag oder Arbeiten bereits begonnen"] },
    sources: [kfwSource],
    related: ["waermepumpe-altbau", "waermepumpe-kosten", "waermepumpe-angebot"],
  },
  {
    slug: "waermepumpe-kosten",
    category: "waermepumpe",
    adGroup: "WP Kosten & Einbau",
    intent: "Die Kosten einer Wärmepumpe einschließlich Einbau verstehen und für das eigene Gebäude ermitteln lassen.",
    title: "Wärmepumpe: Kosten inklusive Einbau ermitteln | ALAB",
    description: "Was kostet eine Wärmepumpe mit Einbau? ALAB prüft Gebäude, Hydraulik, Warmwasser und Elektroarbeiten für einen nachvollziehbaren Projektpreis im Allgäu.",
    eyebrow: "Kosten & Einbau nachvollziehbar planen",
    h1: "Was kostet eine Wärmepumpe inklusive Einbau?",
    intro: "Der Gesamtpreis hängt von Ihrem Gebäude und dem Umbau ab. ALAB erfasst Heizlast, Hydraulik, Warmwasser und Elektroarbeiten – damit Sie die Kosten Ihrer Wärmepumpe inklusive Einbau nachvollziehen können.",
    cta: "Individuelle Kosten berechnen lassen",
    benefits: ["Gerät und Einbau zusammen betrachten", "Umbauaufwand im Bestand prüfen", "Nachvollziehbares Angebot erhalten"],
    heroImage: "/optimized/waermepumpe-bosch-7bd7fd7c72.webp",
    heroAlt: "Bosch Wärmepumpe mit Fundament an einer Hausfassade als Produktbeispiel zur Planung der Einbaukosten",
    heroCaption: "Produktbeispiel · Bosch Wärmepumpe",
    focusTitle: "Diese Faktoren bestimmen Ihre Wärmepumpen-Kosten",
    focusIntro: "Zwei gleich große Häuser können unterschiedliche Anlagen benötigen. Für einen belastbaren Preis prüfen wir drei Bereiche Ihres Projekts.",
    focusItems: [
      { title: "Gebäude & Wärmebedarf", text: "Heizlast, Gebäudezustand und vorhandene Heizflächen bestimmen Geräteleistung und mögliche Anpassungen." },
      { title: "Einbau & Heizraum", text: "Demontage, Hydraulik, Warmwasserspeicher und Leitungswege beeinflussen Material und Montageaufwand." },
      { title: "Außenbereich & Strom", text: "Aufstellfläche, Fundament, Anschlussleitungen und Zählerschrank machen den standortabhängigen Teil des Projekts aus." },
    ],
    servicesTitle: "Wärmepumpe mit Einbau: Diese Positionen prüfen wir",
    services: [
      { title: "Planung & Wärmepumpe", text: "Erforderliche Leistung, Geräteauswahl und die Auslegung des gesamten Systems." },
      { title: "Demontage der Altanlage", text: "Aufwand für Rückbau und die abgestimmten Arbeiten an vorhandener Heiztechnik." },
      { title: "Heizkreis & Warmwasser", text: "Hydraulische Einbindung, nötige Anpassungen und ein passender Warmwasserspeicher." },
      { title: "Fundament & Leitungen", text: "Aufstellung der Außeneinheit, Leitungsführung und Arbeiten am Gebäude." },
      { title: "Elektroinstallation & Zähleranlage", text: "Stromversorgung, Absicherung und erforderliche Änderungen am vorhandenen Zählerschrank." },
      { title: "Inbetriebnahme & Einweisung", text: "Prüfung, Einstellung, Übergabe und Dokumentation der vereinbarten Anlage." },
    ],
    steps: [
      { title: "Eckdaten nennen", text: "Gebäude, bisherige Heizung und Projektort bilden den Einstieg." },
      { title: "Aufwand erfassen", text: "Wir prüfen den Bestand und die für den Einbau notwendigen Arbeiten." },
      { title: "Kosten nachvollziehen", text: "Sie erhalten ein Angebot mit abgestimmtem Umfang und besprechen mögliche Optionen." },
    ],
    faqs: [
      { question: "Warum gibt es hier keinen Pauschalpreis für eine Wärmepumpe?", answer: "Ein Pauschalpreis würde wichtige Unterschiede Ihres Gebäudes ausblenden. Leistung, Speicher, Leitungswege und notwendige Umbauten verändern den Gesamtaufwand. Ein belastbares Angebot entsteht nach der technischen Prüfung und einem klar definierten Leistungsumfang." },
      { question: "Reicht die Wohnfläche, um die Kosten zu berechnen?", answer: "Die Wohnfläche ist nur ein erster Anhaltspunkt. Für die Auslegung zählen auch Wärmeverluste, Heizflächen, Warmwasserbedarf und der Gebäudezustand. Deshalb beziehen wir Heizlast und die vorhandene Technik in die Planung ein." },
      { question: "Welche zusätzlichen Einbaukosten werden häufig übersehen?", answer: "Je nach Projekt sind Rückbau, Fundament, Leitungswege, Speicher und Elektroarbeiten zu berücksichtigen. Wir prüfen diese Schnittstellen frühzeitig, damit Sie den vereinbarten Gesamtumfang beurteilen können und nicht nur den Preis des Geräts sehen." },
      { question: "Wie lassen sich zwei Wärmepumpen-Angebote sinnvoll vergleichen?", answer: "Vergleichen Sie neben Gerät und Leistung auch Planung, Montage, Hydraulik, Warmwasserspeicher, Elektroarbeiten und Inbetriebnahme. Achten Sie außerdem auf ausgeschlossene Leistungen und noch ungeklärte Voraussetzungen. Gleiche Endpreise bedeuten nicht automatisch gleichen Umfang." },
      { question: "Wie berücksichtige ich Förderung in meiner Kostenplanung?", answer: "Betrachten Sie zuerst die vollständigen Projektkosten. Eine mögliche Förderung wird anschließend gesondert anhand des passenden Programms geprüft. Ein erwarteter Zuschuss sollte nicht wie eine bereits bestätigte Preisreduzierung behandelt werden." },
      { question: "Sind Anschaffungskosten und laufende Heizkosten dasselbe?", answer: "Nein. Das Angebot beschreibt die vereinbarten Investitionskosten. Die späteren Betriebskosten hängen unter anderem von Wärmebedarf, Anlageneinstellung, Stromtarif und tatsächlicher Nutzung ab. Eine PV-Anlage kann ergänzend betrachtet werden, ersetzt aber keine projektbezogene Berechnung." },
    ],
    formTitle: "Was kostet die Wärmepumpe für Ihr Gebäude?",
    formIntro: "Für einen belastbaren Preis benötigen wir einige Angaben zu Ihrem Gebäude. Starten Sie mit Standort und Heizsituation; weitere Details klären wir persönlich.",
    projectType: "Wärmepumpe – Kosten inklusive Einbau",
    qualifier: { label: "Welche Ausgangslage trifft zu?", options: ["Bestandsgebäude mit Gasheizung", "Bestandsgebäude mit Ölheizung", "Andere bestehende Heizung", "Neubau", "Noch in der Orientierung"] },
    related: ["waermepumpe-angebot", "waermepumpe-altbau", "waermepumpe-foerderung"],
  },
];
