import type { LandingPage } from "./types";

export const solarPages: LandingPage[] = [
  {
    slug: "photovoltaik-allgaeu",
    regional: true,
    category: "photovoltaik",
    adGroup: "PV Fachbetrieb Region",
    intent: "Einen regionalen Photovoltaik-Fachbetrieb für Planung und eigene Installation finden.",
    title: "Photovoltaik im Allgäu & Mindelheim | ALAB",
    description: "Photovoltaik vom Ingenieurbüro und Elektrofachbetrieb aus Mindelheim: Planung, eigene Montage, Netzanschluss und Inbetriebnahme. PV-Projekt besprechen.",
    eyebrow: "Photovoltaik vom Fachbetrieb aus Mindelheim",
    h1: "Photovoltaik-Fachbetrieb für Mindelheim, Unterallgäu & Allgäu",
    intro: "Ihre Photovoltaikanlage braucht ein passendes Konzept und eine saubere Umsetzung. ALAB plant und installiert Ihre PV-Anlage – vom Dach bis zum Zählerschrank, mit einem persönlichen Ansprechpartner aus Mindelheim.",
    cta: "PV-Projekt besprechen",
    benefits: ["Ingenieurbüro & eigener Elektrofachbetrieb", "Dachmontage und Elektroanschluss aus einer Hand", "Persönliche Begleitung vor Ort"],
    heroImage: "/optimized/joerg-seider-5d10ae1555.webp",
    heroAlt: "Photovoltaikanlage auf einem Wohnhaus aus den ALAB-Referenzen",
    heroCaption: "Einblick in unsere Arbeit: Photovoltaik auf einem Wohnhaus",
    focusTitle: "Ein Ansprechpartner. Vom Dach bis zum Anschluss.",
    focusIntro: "Sie möchten wissen, wer Ihre Anlage plant, wer sie montiert und wer nach der Inbetriebnahme erreichbar ist. Bei ALAB gehören Ingenieurplanung und handwerkliche Umsetzung zusammen.",
    focusItems: [
      { title: "Ihr Gebäude im Blick", text: "Wir prüfen Dach, Verschattung, Stromverbrauch und Zähleranlage gemeinsam. So passt die Planung zur tatsächlichen Situation vor Ort." },
      { title: "Montage und Elektrik abgestimmt", text: "Module, Leitungswege, Wechselrichter und Netzanschluss werden als Gesamtsystem geplant. Dach- und Elektroarbeiten greifen ineinander." },
      { title: "In der Region erreichbar", text: "Unser Standort ist Mindelheim. Für Ihr Vorhaben im Unterallgäu und Allgäu klären wir den Vor-Ort-Termin persönlich mit Ihnen." },
    ],
    servicesTitle: "Was wir für Ihre Photovoltaikanlage übernehmen",
    services: [
      { title: "Beratung & Anlagenplanung", text: "Dachbelegung, Komponenten und Anlagengröße auf Grundlage Ihres Hauses und Verbrauchs." },
      { title: "Eigene Montage", text: "Unterkonstruktion, Module und DC-Verkabelung fachgerecht aufeinander abgestimmt." },
      { title: "Elektroanschluss", text: "Wechselrichter, AC-Anschluss und Prüfung notwendiger Anpassungen der Zähleranlage." },
      { title: "Anmeldung & Inbetriebnahme", text: "Abstimmung mit dem Netzbetreiber, technische Prüfung und dokumentierte Übergabe im vereinbarten Umfang." },
      { title: "Speicher & Wallbox", text: "Optional gemeinsam auslegen, damit Erzeugung, Haushalt und Laden zusammenpassen." },
      { title: "Monitoring & Service", text: "Anlagenüberwachung und Wartung nach Ihrem Bedarf und dem vereinbarten Serviceumfang." },
    ],
    steps: [
      { title: "Projekt schildern", text: "Nennen Sie uns Ihren Standort, die Gebäudeart und Ihre Wünsche." },
      { title: "Vor Ort prüfen", text: "Wir klären Dach, Elektroinstallation und die technischen Rahmenbedingungen." },
      { title: "Konzept & Angebot", text: "Sie erhalten eine passende Anlagenplanung mit nachvollziehbarem Leistungsumfang." },
      { title: "Installieren & übergeben", text: "Wir setzen die Anlage um und begleiten Anschluss, Inbetriebnahme und Einweisung." },
    ],
    faqs: [
      { question: "In welcher Region installiert ALAB Photovoltaikanlagen?", answer: "ALAB sitzt in Mindelheim und betreut PV-Projekte im Unterallgäu und Allgäu. Teilen Sie uns Ihre Postleitzahl mit; wir klären direkt, wie wir Ihr Vorhaben vor Ort begleiten können." },
      { question: "Übernimmt ALAB Dachmontage und Elektroanschluss?", answer: "Ja. ALAB verbindet Ingenieurplanung mit eigener Montage und einem eigenen Elektrofachbetrieb. Dachseitige DC-Arbeiten und der AC-Anschluss werden gemeinsam geplant; der konkrete Umfang steht im Angebot." },
      { question: "Muss mein Zählerschrank für Photovoltaik erneuert werden?", answer: "Das lässt sich erst nach einer Bestandsprüfung beantworten. Wir prüfen Platz, Zustand und Anschlussanforderungen. Ob eine Anpassung oder ein Austausch erforderlich ist, erläutern wir vor der Umsetzung." },
      { question: "Können Speicher, Wallbox und Wärmepumpe mitgeplant werden?", answer: "Ja. Vorhandene und geplante Verbraucher fließen in das Anlagenkonzept ein. Dabei prüfen wir auch passende Schnittstellen und die Möglichkeiten eines gemeinsamen Energiemanagements." },
      { question: "Wer kümmert sich um Anmeldung und spätere Betreuung?", answer: "Wir begleiten die technische Anmeldung beim Netzbetreiber und die Inbetriebnahme im vereinbarten Umfang. Bei der Übergabe klären wir auch die Aufgaben des Anlagenbetreibers sowie passende Möglichkeiten für Monitoring und Wartung." },
      { question: "Welche Angaben helfen beim ersten Gespräch?", answer: "Standort, Dachart und ungefährer Jahresstromverbrauch genügen für den Einstieg. Fotos von Dach und Zählerschrank sowie Angaben zu einem geplanten E-Auto oder einer Wärmepumpe helfen bei der weiteren Prüfung." },
    ],
    formTitle: "Besprechen wir Ihr PV-Projekt in der Region.",
    formIntro: "Ein paar Angaben zu Ihrem Haus reichen für den ersten Kontakt. Technische Details klären wir gemeinsam.",
    projectType: "Photovoltaik privat",
    qualifier: { label: "Was möchten Sie umsetzen?", options: ["Neue PV-Anlage", "PV-Anlage mit Speicher", "PV, Speicher und Wallbox", "Bestehende Anlage erweitern", "Ich möchte mich zunächst beraten lassen"] },
    related: ["photovoltaik-angebot", "photovoltaik-mit-speicher", "zaehlerschrank-modernisieren"],
  },
  {
    slug: "photovoltaik-angebot",
    category: "photovoltaik",
    adGroup: "PV Kaufen & Angebot",
    intent: "Eine Photovoltaikanlage kaufen und ein konkretes Komplettangebot für das eigene Haus erhalten.",
    title: "Photovoltaikanlage kaufen & Angebot anfordern | ALAB",
    description: "Individuelles PV-Komplettangebot: Planung, Module, Montage und Elektroanschluss. Optional mit Speicher. Jetzt kostenloses Angebot anfragen.",
    eyebrow: "Ihr PV-Angebot: Planung und Installation aus einer Hand",
    h1: "Photovoltaikanlage kaufen – individuelles Komplettangebot",
    intro: "Sie möchten eine Photovoltaikanlage kaufen? Wir prüfen Ihr Dach und Ihren Strombedarf und erstellen ein passendes Angebot für Planung, Montage und Elektroanschluss. Auf Wunsch mit Speicher und Wallbox – vom Fachbetrieb.",
    cta: "Kostenloses PV-Angebot anfordern",
    benefits: ["Auf Ihr Dach und Ihren Verbrauch ausgelegt", "Klar beschriebener Leistungsumfang", "Planung & eigene Installation"],
    heroImage: "/optimized/joerg-seider-5d10ae1555.webp",
    heroAlt: "Installierte Photovoltaikanlage auf einem Ziegeldach aus den ALAB-Referenzen",
    heroCaption: "ALAB-Projekteinblick: von der Planung zur Anlage auf dem Dach",
    focusTitle: "Ein Angebot, das zu Ihrem Haus passt.",
    focusIntro: "Der Anlagenpreis in Ihrem unverbindlichen Angebot ergibt sich aus Dach, Strombedarf und Anschlussaufwand. Deshalb prüfen wir die entscheidenden Punkte, bevor wir Ihnen ein Anlagenkonzept anbieten.",
    focusItems: [
      { title: "Passende Anlagengröße", text: "Nutzbare Dachfläche, Verschattung und heutiger sowie geplanter Verbrauch bilden die Grundlage der Auslegung." },
      { title: "Umfang nachvollziehen", text: "Sie sehen, welche Komponenten und Arbeiten enthalten sind und welche Optionen zusätzlich sinnvoll sein können." },
      { title: "Anschluss mitgeplant", text: "Leitungswege und Zählerschrank fließen früh ein. So können erforderliche Elektroarbeiten im Angebot berücksichtigt werden." },
    ],
    servicesTitle: "Diese Bausteine gehören in Ihr PV-Angebot",
    services: [
      { title: "Technische Planung", text: "Dachbelegung, Wechselrichterauslegung und ein Konzept für den Elektroanschluss." },
      { title: "Module & Montage", text: "Passende PV-Module, Unterkonstruktion und abgestimmte Dachmontage." },
      { title: "Wechselrichter & Verkabelung", text: "DC- und AC-Verbindungen sowie Schutzkomponenten für das geplante System." },
      { title: "Zähleranlage", text: "Prüfung des Bestands und nachvollziehbare Berücksichtigung erforderlicher Anpassungen." },
      { title: "Speicher als Option", text: "Auf Verbrauch und PV-Erzeugung abgestimmte Speicherlösung, wenn für Ihr Vorhaben sinnvoll." },
      { title: "Anschluss & Übergabe", text: "Netzbetreiber-Abstimmung, Inbetriebnahme, Dokumentation und Einweisung im vereinbarten Umfang." },
    ],
    steps: [
      { title: "Anfrage", text: "Sie nennen uns Standort, Gebäude und Ihren ungefähren Stromverbrauch." },
      { title: "Technische Prüfung", text: "Wir klären Dach, Leitungswege und Anschlussbedingungen." },
      { title: "Planung & Angebot", text: "Sie erhalten das Anlagenkonzept mit Leistungen und passenden Optionen." },
      { title: "Installation", text: "Nach Beauftragung stimmen wir die Montage und Elektroarbeiten mit Ihnen ab." },
      { title: "Anschluss & Inbetriebnahme", text: "Wir begleiten die Anmeldung, prüfen die Anlage und weisen Sie in die Bedienung ein." },
    ],
    faqs: [
      { question: "Ist die Anfrage für ein PV-Angebot kostenlos?", answer: "Ja, die Angebotsanfrage ist kostenlos und unverbindlich. Sollte für Ihr Vorhaben eine gesonderte, kostenpflichtige Planungsleistung sinnvoll sein, wird diese vorab mit Ihnen abgestimmt." },
      { question: "Was ist im Komplettangebot enthalten?", answer: "Das Angebot beschreibt die vereinbarten Planungsleistungen, Komponenten, Montage- und Elektroarbeiten sowie die Inbetriebnahme. Notwendige Anpassungen der Zähleranlage und gewünschte Optionen wie Speicher oder Wallbox werden konkret ausgewiesen." },
      { question: "Welche Unterlagen braucht ALAB für ein Angebot?", answer: "Hilfreich sind Ihre Adresse, Dachfotos und die letzte Stromabrechnung. Fotos der Zähleranlage und Angaben zu geplanten Verbrauchern ergänzen die Grundlage. Fehlende Details klären wir im Gespräch oder bei der technischen Prüfung." },
      { question: "Kann ich ein Angebot mit und ohne Speicher erhalten?", answer: "Ja. Wir können beide Varianten gegenüberstellen. Ob ein Speicher zu Ihrem Haus passt, hängt insbesondere davon ab, wann Sie Strom verbrauchen und wie viel Solarstrom dafür verfügbar ist." },
      { question: "Ist das Ergebnis des Solarrechners bereits ein verbindliches Angebot?", answer: "Nein. Der Solarrechner dient der ersten Orientierung anhand Ihrer Eingaben und der hinterlegten Annahmen. Ein individuelles Angebot setzt die technische Prüfung Ihres Gebäudes und der Anschlussbedingungen voraus." },
      { question: "Wann kann die PV-Anlage installiert werden?", answer: "Der Termin hängt vom Projektumfang, der technischen Klärung, Komponentenverfügbarkeit und der Abstimmung mit dem Netzbetreiber ab. Einen realistischen Ablauf besprechen wir mit Ihnen im Rahmen der Angebotsphase." },
    ],
    formTitle: "Jetzt Ihr persönliches PV-Angebot anfordern.",
    formIntro: "Beschreiben Sie kurz Ihr Vorhaben. Wir klären mit Ihnen die nächsten Schritte zur technischen Prüfung und zum passenden Angebot.",
    projectType: "Photovoltaik-Angebot",
    qualifier: { label: "Welche Lösung möchten Sie anfragen?", options: ["PV-Anlage ohne Speicher", "PV-Anlage mit Speicher", "PV, Speicher und Wallbox", "Varianten vergleichen", "Noch offen – bitte beraten"] },
    earlyForm: true,
    solarCalculator: true,
    related: ["photovoltaik-mit-speicher", "photovoltaik-allgaeu"],
  },
  {
    slug: "photovoltaik-mit-speicher",
    category: "photovoltaik",
    adGroup: "PV mit Speicher",
    intent: "Eine Photovoltaikanlage mit passend dimensioniertem Batteriespeicher für das Eigenheim planen.",
    title: "Photovoltaik mit Speicher für Ihr Zuhause | ALAB",
    description: "PV-Anlage und Batteriespeicher passend zu Ihrem Verbrauch planen: Solarstrom auch abends nutzen. Mit ALAB Ihr Gesamtsystem abstimmen.",
    eyebrow: "Photovoltaik und Speicher für Ihr Zuhause",
    h1: "Photovoltaik mit Speicher – Solarstrom auch abends nutzen",
    intro: "Ihr Dach erzeugt tagsüber Strom. Ein passend ausgelegter Speicher kann einen Teil davon für den Abend bereitstellen. ALAB plant PV-Anlage, Batteriespeicher und Energiemanagement gemeinsam – passend zu Ihrem Alltag.",
    cta: "PV + Speicher planen lassen",
    benefits: ["An Ihren Tagesablauf angepasst", "PV und Speicher gemeinsam ausgelegt", "Wärmepumpe & E-Auto mitgedacht"],
    heroImage: "/optimized/joerg-seider-5d10ae1555.webp",
    heroAlt: "Private PV-Dachanlage aus den ALAB-Referenzen als Teil eines häuslichen Energiesystems",
    heroCaption: "Solarstrom vom eigenen Dach, Projektfoto aus unseren Referenzen",
    focusTitle: "Die passende Speichergröße beginnt mit Ihrem Alltag.",
    focusIntro: "Ein großer Speicher ist allein noch kein gutes Konzept. Entscheidend ist, wie viel Solarstrom übrig bleibt und wann Ihr Haushalt ihn benötigt.",
    focusItems: [
      { title: "Wann brauchen Sie Strom?", text: "Abendverbrauch, Nachtbedarf und Anwesenheitszeiten zeigen, welcher Anteil Ihres Verbrauchs durch gespeicherten Solarstrom gedeckt werden kann." },
      { title: "Was liefert Ihr Dach?", text: "PV-Leistung, Ausrichtung und Verschattung bestimmen die Erzeugung. Die Speicherkapazität muss dazu passen und regelmäßig nutzbar sein." },
      { title: "Was kommt künftig dazu?", text: "Wärmepumpe, Wallbox und E-Auto verändern den Strombedarf. Ladezeiten und steuerbare Verbraucher beziehen wir in das Gesamtkonzept ein." },
    ],
    servicesTitle: "Ein abgestimmtes System für Erzeugung und Verbrauch",
    services: [
      { title: "Verbrauchsanalyse", text: "Jahresverbrauch und typische Nutzungszeiten als Grundlage der Auslegung." },
      { title: "PV-Planung", text: "Dachbelegung und Erzeugungskonzept passend zu Gebäude und Verbrauch." },
      { title: "Speicherauslegung", text: "Nutzbare Kapazität, Leistung und Systemkompatibilität gemeinsam betrachten." },
      { title: "Energiemanagement", text: "Geeignete Verbraucher und verfügbare Schnittstellen aufeinander abstimmen." },
      { title: "Montage & Elektroarbeiten", text: "Anlage und Speicher installieren, anschließen und gemeinsam in Betrieb nehmen." },
      { title: "Einweisung & Monitoring", text: "Erzeugung, Ladestand und Stromflüsse im eingesetzten System nachvollziehen." },
    ],
    steps: [
      { title: "Alltag verstehen", text: "Wir besprechen Verbrauch, Nutzungszeiten und geplante größere Verbraucher." },
      { title: "System dimensionieren", text: "Dach, PV-Erzeugung, Speichergröße und Elektroinstallation werden gemeinsam geprüft." },
      { title: "Varianten besprechen", text: "Sie erhalten ein Anlagenkonzept mit nachvollziehbarem Nutzen und passendem Leistungsumfang." },
      { title: "Installieren & einstellen", text: "Wir nehmen die Komponenten in Betrieb und erklären Ihnen die Bedienung." },
    ],
    faqs: [
      { question: "Wie groß sollte mein Batteriespeicher sein?", answer: "Das hängt von PV-Erzeugung, Tagesablauf und Strombedarf außerhalb der Sonnenstunden ab. Wir betrachten nutzbare Kapazität und Ladeleistung gemeinsam. Eine Dimensionierung allein anhand der Haushaltsgröße greift häufig zu kurz." },
      { question: "Kann ich damit meinen gesamten Strombedarf selbst decken?", answer: "Eine vollständige Versorgung lässt sich daraus nicht ableiten. Wetter, Jahreszeit und Verbrauch beeinflussen den Netzbezug. Ein Heimspeicher verschiebt verfügbare Energie innerhalb begrenzter Zeiträume; er überbrückt keine längeren Phasen mit zu wenig PV-Erzeugung." },
      { question: "Lohnt sich ein Speicher, wenn tagsüber niemand zu Hause ist?", answer: "Ein höherer Abendverbrauch kann für einen Speicher sprechen. Ob sich die zusätzliche Investition rechnet, prüfen wir anhand von Erzeugung, Verbrauch, nutzbarer Kapazität und den Kosten der konkreten Lösung." },
      { question: "Kann meine Wärmepumpe mit Solarstrom versorgt werden?", answer: "PV-Strom kann zur Versorgung einer Wärmepumpe beitragen. Im Winter fällt ein hoher Heizbedarf jedoch oft mit geringerer PV-Erzeugung zusammen. Deshalb berücksichtigen wir den Jahresverlauf und die technischen Möglichkeiten zur Steuerung." },
      { question: "Wie passen Speicher und E-Auto zusammen?", answer: "Das hängt vor allem von Ihren Ladezeiten ab. Lädt das Auto tagsüber zu Hause, kann direkter PV-Verbrauch sinnvoll sein. Das Energiemanagement soll Prioritäten zwischen Haushalt, Speicher und Wallbox passend zu Ihrem Alltag setzen." },
      { question: "Lässt sich ein Speicher an meiner vorhandenen PV-Anlage nachrüsten?", answer: "Das kann möglich sein. Wir prüfen Wechselrichter, Anlagenaufbau, Messkonzept und Aufstellbedingungen. Daraus ergibt sich, welche Speicherlösung kompatibel ist und welche Umbauten erforderlich wären." },
    ],
    formTitle: "Wie nutzen Sie Strom? Planen wir das passende System.",
    formIntro: "Teilen Sie uns mit, ob bereits eine PV-Anlage besteht und welche Verbraucher Sie einbinden möchten.",
    projectType: "Photovoltaik mit Speicher",
    qualifier: { label: "Wie ist Ihre Ausgangssituation?", options: ["Neue PV-Anlage mit Speicher", "Speicher für vorhandene PV-Anlage", "PV und Speicher mit Wärmepumpe", "PV und Speicher mit Wallbox", "Passende Lösung noch offen"] },
    related: ["photovoltaik-angebot", "waermepumpe-altbau", "zaehlerschrank-modernisieren"],
  },
  {
    slug: "photovoltaik-hallendach-industrie",
    category: "gewerbe",
    adGroup: "Hallendach & Industrie",
    intent: "Die technische Eignung eines Hallen- oder Industriedachs für eine gewerbliche PV-Anlage prüfen.",
    title: "Photovoltaik für Hallendach & Industrie | ALAB",
    description: "Gewerbedach für Photovoltaik prüfen: Dachzustand, Statik, Lastgang und Netzanschluss zusammen planen. ALAB begleitet Ihr Hallen- und Industrieprojekt.",
    eyebrow: "Technische Projektentwicklung für Gewerbe & Industrie",
    h1: "Photovoltaik für Hallendächer & Industrie",
    intro: "Aus einer großen Dachfläche wird erst mit einem tragfähigen Konzept eine nutzbare Energieanlage. ALAB prüft Dach, Verbrauch und Anschlussbedingungen und plant Ihre gewerbliche PV-Anlage bis zur Umsetzung.",
    cta: "Gewerbedach prüfen lassen",
    benefits: ["Dach und Netzanschluss gemeinsam betrachtet", "Lastgang als Planungsgrundlage", "Ingenieurplanung & eigene Ausführung"],
    heroImage: "/optimized/gewerbedach-pv-286c2c447c.webp",
    heroAlt: "Photovoltaikanlage auf dem Flachdach einer Gewerbehalle – Projekt von ALAB Energiesysteme",
    heroCaption: "ALAB-Projekteinblick: Photovoltaik auf einem Gewerbedach",
    focusTitle: "Zuerst die Machbarkeit. Dann die Anlagenleistung.",
    focusIntro: "Bei Produktionshallen, Logistikgebäuden und Gewerbeimmobilien entscheiden Dach, Betrieb und Netzanschluss gemeinsam über das Anlagenkonzept.",
    focusItems: [
      { title: "Dach & Tragfähigkeit", text: "Dachaufbau, Zustand, Belegungsflächen und vorhandene Statikunterlagen prüfen. Erforderliche Nachweise und Fachplanungen werden früh abgestimmt." },
      { title: "Anschluss & Schutzkonzept", text: "Anschlussleistung, Zählerkonzept und Anforderungen an Nieder- oder Mittelspannung klären. Brandschutz und Überspannungsschutz gehören in die Planung." },
      { title: "Verbrauch & Betrieb", text: "Lastgang, Betriebszeiten und geplante Erweiterungen bestimmen die Eigenverbrauchsmöglichkeiten. Montageablauf und Zugänglichkeit stimmen wir mit Ihrem Betrieb ab." },
    ],
    servicesTitle: "Technik und Umsetzung für Ihr Hallenprojekt",
    services: [
      { title: "Technische Bestandsaufnahme", text: "Dachflächen, Unterlagen, Elektroverteilung und Anschlussbedingungen strukturiert erfassen." },
      { title: "Belegungs- & Ertragskonzept", text: "Dachnutzung, Ausrichtung, Verschattung und Wartungszugänge zusammen planen." },
      { title: "Netzanschlusskonzept", text: "Netzbetreiber einbinden und erforderliche Anschluss- und Messlösungen abstimmen." },
      { title: "Montage & Elektrotechnik", text: "Unterkonstruktion, Module, Leitungswege, Wechselrichter und Schutztechnik umsetzen." },
      { title: "Speicher & Ladeinfrastruktur", text: "Zusätzliche Verbraucher und Speicheroptionen anhand des Lastprofils bewerten." },
      { title: "Dokumentation & Betrieb", text: "Übergabe, Anlagenüberwachung und Wartung planen; Vermarktungsfragen bei Bedarf früh berücksichtigen." },
    ],
    steps: [
      { title: "Standort & Unterlagen", text: "Sie nennen Dachfläche, Dachart, Nutzung und vorhandene Verbrauchsdaten." },
      { title: "Machbarkeit klären", text: "Wir prüfen technische Schnittstellen und stimmen offene Nachweise sowie den Netzanschluss ab." },
      { title: "Konzept & Investition", text: "Anlagenvarianten und Wirtschaftlichkeit schaffen die Grundlage für Ihre Entscheidung." },
      { title: "Realisierung abstimmen", text: "Montage, betriebliche Abläufe, Anschluss und Inbetriebnahme werden koordiniert." },
      { title: "Übergeben & betreuen", text: "Sie erhalten Dokumentation und Einweisung; Monitoring und Wartung werden nach Bedarf vereinbart." },
    ],
    faqs: [
      { question: "Welche Hallendächer kommen für Photovoltaik infrage?", answer: "Die Eignung hängt unter anderem von Tragfähigkeit, Dachaufbau, Zustand und nutzbarer Fläche ab. Lichtkuppeln, Dachaufbauten und notwendige Zugänge beeinflussen die Belegung. Die Dachart allein reicht für eine Zusage nicht aus." },
      { question: "Wer prüft die Statik und den Brandschutz?", answer: "Wir sichten die verfügbaren Unterlagen und klären, welche Nachweise für das Projekt benötigt werden. Erforderliche statische Nachweise und Fachplanungen müssen durch die dafür zuständigen Fachleute erfolgen und werden mit der PV-Planung abgestimmt." },
      { question: "Ist ein Anschluss an die Mittelspannung erforderlich?", answer: "Das lässt sich nicht allein aus der Dachfläche ableiten. Maßgeblich sind das konkrete Anlagenkonzept, der vorhandene Anschluss und die Vorgaben des Netzbetreibers. Wir klären die Anschlussvariante im Rahmen der technischen Planung." },
      { question: "Kann die Anlage während des laufenden Betriebs gebaut werden?", answer: "Der Montageablauf lässt sich häufig mit dem Betrieb abstimmen. Ob Abschaltungen, Sperrbereiche oder besondere Sicherheitsmaßnahmen erforderlich sind, prüfen wir vorab. Notwendige Eingriffe werden mit den betrieblichen Verantwortlichen geplant." },
      { question: "Was passiert, wenn das Dach zuerst saniert werden muss?", answer: "Dann sollten Dachsanierung und PV-Projekt gemeinsam geplant werden. Restnutzungsdauer, Befestigung und spätere Zugänglichkeit beeinflussen das Konzept. So lässt sich der Aufwand für eine spätere Demontage möglichst früh berücksichtigen." },
      { question: "Sind Speicher und Direktvermarktung Teil der Planung?", answer: "Speicher werden anhand von Lastgang und Nutzungsziel bewertet. Ob Direktvermarktung für das Projekt relevant ist, muss anhand des Anlagen- und Betriebskonzepts sowie der geltenden Rahmenbedingungen gesondert geklärt werden." },
    ],
    formTitle: "Prüfen wir das Potenzial Ihres Gewerbedachs.",
    formIntro: "Standort, Dachart und eine ungefähre Dachfläche reichen für den Einstieg. Vorhandene Lastgänge und Planunterlagen besprechen wir im nächsten Schritt.",
    projectType: "Photovoltaik Hallendach / Industrie",
    qualifier: { label: "Welche Immobilie möchten Sie prüfen lassen?", options: ["Produktions- oder Industriehalle", "Logistik- oder Lagerhalle", "Gewerbeimmobilie mit mehreren Nutzern", "Halle mit geplanter Dachsanierung", "Anderes Gewerbedach"] },
    related: ["photovoltaik-gewerbe", "gewerbe-pv-wirtschaftlichkeit", "gewerbe-pv-speicher"],
  },
  {
    slug: "photovoltaik-gewerbe",
    category: "gewerbe",
    adGroup: "PV für Gewerbe",
    intent: "Den betrieblichen Stromverbrauch durch eine passend geplante gewerbliche PV-Anlage teilweise selbst decken.",
    title: "Photovoltaik für Gewerbe & Unternehmen | ALAB",
    description: "Photovoltaik für Ihren Betrieb: Eigenverbrauch, Lastprofil und Wirtschaftlichkeit zusammen planen. Ingenieurplanung und Installation von ALAB.",
    eyebrow: "Photovoltaik für Unternehmen: eigenen Strom nutzen",
    h1: "Photovoltaik für Gewerbe – Energiekosten nachhaltig reduzieren",
    intro: "Wenn Ihr Betrieb Strom braucht, kann das eigene Dach einen Teil davon liefern. ALAB plant gewerbliche Photovoltaikanlagen anhand Ihres Lastprofils, prüft die Wirtschaftlichkeit und übernimmt Planung und Installation.",
    cta: "Wirtschaftlichkeit prüfen lassen",
    benefits: ["Auslegung nach betrieblichem Verbrauch", "Nachvollziehbare Wirtschaftlichkeitsbetrachtung", "Planung, Anschluss & Installation"],
    heroImage: "/optimized/gewerbedach-pv-286c2c447c.webp",
    heroAlt: "Photovoltaikanlage auf dem Flachdach einer Gewerbehalle – Projekt von ALAB Energiesysteme",
    heroCaption: "ALAB-Projekteinblick: Photovoltaik auf einem Gewerbedach",
    focusTitle: "Ihr Stromverbrauch gibt die Richtung vor.",
    focusIntro: "Für eine gewerbliche PV-Anlage zählt, wie Erzeugung und Verbrauch zeitlich zusammenpassen. Wir betrachten Ihren Betriebsalltag und entwickeln daraus das passende Anlagenkonzept.",
    focusItems: [
      { title: "Betriebszeiten berücksichtigen", text: "Produktion, Kühlung, Büro und Werkstatt haben unterschiedliche Verbrauchsmuster. Diese Unterschiede fließen in die Auslegung ein." },
      { title: "Eigenverbrauch bewerten", text: "Wir stellen erwartete Erzeugung und Lastprofil gegenüber. Direkt genutzter Solarstrom, Überschüsse und verbleibender Netzbezug werden getrennt betrachtet." },
      { title: "Entscheidungen vorbereiten", text: "Anlagengröße, Investition und laufender Betrieb werden als Varianten bewertet. Annahmen bleiben nachvollziehbar und können gemeinsam angepasst werden." },
    ],
    servicesTitle: "Vom Verbrauchsprofil zur betriebsbereiten Anlage",
    services: [
      { title: "Lastprofil auswerten", text: "Verbrauchsdaten, Betriebszeiten und künftige Lasten erfassen." },
      { title: "Wirtschaftlichkeit prüfen", text: "Eigenverbrauch, Überschüsse, Investition und laufende Kosten gemeinsam bewerten." },
      { title: "PV-Anlage planen", text: "Dachbelegung, Komponenten, Elektroanschluss und Messkonzept abstimmen." },
      { title: "Fachgerecht installieren", text: "Montage und Elektroarbeiten mit den Abläufen im Unternehmen koordinieren." },
      { title: "Anschluss & Inbetriebnahme", text: "Netzbetreiber einbinden, Anlage prüfen und die Übergabe dokumentieren." },
      { title: "Monitoring & Wartung", text: "Erzeugung sichtbar machen und passende Maßnahmen für den Anlagenbetrieb vereinbaren." },
    ],
    steps: [
      { title: "Betrieb kennenlernen", text: "Standort, Strombedarf, Betriebszeiten und Erweiterungspläne besprechen." },
      { title: "Potenzial analysieren", text: "Dach, Lastprofil und Anschlussbedingungen technisch und wirtschaftlich bewerten." },
      { title: "Konzept entscheiden", text: "Leistungsumfang, Anlagenvariante und Projektrahmen gemeinsam festlegen." },
      { title: "Umsetzen & betreiben", text: "Installieren, anschließen und den Betrieb mit Dokumentation und Monitoring vorbereiten." },
    ],
    faqs: [
      { question: "Für welche Unternehmen ist eine PV-Anlage interessant?", answer: "Ein relevanter Stromverbrauch und eine geeignete Fläche sind gute Ausgangspunkte. Besonders wichtig ist die zeitliche Übereinstimmung von Verbrauch und PV-Erzeugung. Ob sich die Investition für Ihren Betrieb rechnet, wird projektbezogen geprüft." },
      { question: "Was bedeutet Eigenverbrauch bei Gewerbe-PV?", answer: "Eigenverbrauch ist der Anteil des erzeugten Solarstroms, den Ihr Betrieb selbst nutzt. Dafür müssen Erzeugung und Verbrauch zeitlich zusammenpassen oder durch geeignete Speicher und steuerbare Verbraucher aufeinander abgestimmt werden." },
      { question: "Reicht der Jahresstromverbrauch für die Planung?", answer: "Für eine erste Einordnung ist er hilfreich. Ein Lastgang zeigt genauer, wann Ihr Unternehmen Strom bezieht. So lassen sich Eigenverbrauch und mögliche Anlagenvarianten genauer bewerten als mit einer Jahreszahl allein." },
      { question: "Was ist an Wochenenden oder bei Betriebsferien?", answer: "Auch solche Zeiträume gehören in die Analyse. Bei geringem Verbrauch können Überschüsse entstehen. Wir berücksichtigen den Jahresverlauf und prüfen, wie Einspeisung, Speicher oder andere Verbraucher zum Betriebskonzept passen." },
      { question: "Können künftige Maschinen oder Ladepunkte berücksichtigt werden?", answer: "Ja. Geplante Erweiterungen sollten möglichst früh benannt werden. Zusätzliche Lasten beeinflussen Anlagengröße, Anschlussleistung und Energiemanagement; bei noch unsicheren Plänen können verschiedene Szenarien gegenübergestellt werden." },
      { question: "Welche Betreuung ist nach der Inbetriebnahme möglich?", answer: "ALAB bietet Anlagenmonitoring und Wartungsleistungen. Im Projekt klären wir, welcher Umfang für Ihre Anlage sinnvoll ist und welche Leistungen Sie beauftragen möchten. Die vereinbarte Dokumentation gehört zur Übergabe." },
    ],
    formTitle: "Was kann Solarstrom für Ihren Betrieb leisten?",
    formIntro: "Nennen Sie uns Standort, Unternehmensnutzung und Ihren ungefähren Strombedarf. Wir besprechen, welche Daten für die Potenzialanalyse benötigt werden.",
    projectType: "Photovoltaik Gewerbe",
    qualifier: { label: "Wann fällt Ihr Stromverbrauch überwiegend an?", options: ["Werktags tagsüber", "Mehrschicht- oder durchgehender Betrieb", "Starker Abend- oder Nachtverbrauch", "Saisonal wechselnd", "Lastprofil noch nicht bekannt"] },
    related: ["gewerbe-pv-wirtschaftlichkeit", "gewerbe-pv-speicher", "photovoltaik-hallendach-industrie"],
  },
  {
    slug: "gewerbe-pv-speicher",
    category: "gewerbe",
    adGroup: "Speicher & Eigenverbrauch",
    intent: "Anhand des Lastgangs prüfen, wie Batteriespeicher den gewerblichen Eigenverbrauch und das Lastmanagement unterstützen können.",
    title: "Gewerbe-PV mit Batteriespeicher planen | ALAB",
    description: "Gewerbespeicher anhand Ihres Lastgangs planen: Eigenverbrauch, Lastspitzen und Ladeinfrastruktur gemeinsam bewerten. Jetzt Lastprofil mit ALAB analysieren.",
    eyebrow: "Gewerbespeicher: Auslegung anhand Ihres Lastgangs",
    h1: "Gewerbe-PV mit Batteriespeicher – Eigenverbrauch gezielt erhöhen",
    intro: "Ihr Betrieb verbraucht auch außerhalb der Sonnenstunden Strom? ALAB prüft, ob ein Batteriespeicher zu Ihrem Lastgang passt – und wie PV-Anlage, Lastspitzen und Ladeinfrastruktur gemeinsam gesteuert werden können.",
    cta: "Lastprofil analysieren lassen",
    benefits: ["Verbrauchsdaten statt pauschaler Speichergröße", "Kapazität und Leistung getrennt auslegen", "Energiemanagement für den Betrieb"],
    heroImage: "/optimized/gewerbedach-pv-286c2c447c.webp",
    heroAlt: "Photovoltaikanlage auf dem Flachdach einer Gewerbehalle – Projekt von ALAB Energiesysteme",
    heroCaption: "ALAB-Projekteinblick: Photovoltaik auf einem Gewerbedach",
    focusTitle: "Was soll der Speicher in Ihrem Betrieb leisten?",
    focusIntro: "Eigenverbrauch und Lastspitzen stellen unterschiedliche Anforderungen. Bevor wir ein System auslegen, definieren wir seinen konkreten Einsatzzweck.",
    focusItems: [
      { title: "Solarstrom später nutzen", text: "Ein Speicher kann geeignete PV-Überschüsse für spätere Verbrauchszeiten bereitstellen. Dazu vergleichen wir Erzeugung und zeitaufgelösten Lastgang." },
      { title: "Lastspitzen untersuchen", text: "Ob eine Begrenzung von Bezugsspitzen technisch und wirtschaftlich sinnvoll ist, hängt von Dauer, Leistung, Tarifstruktur und verfügbarem Ladezustand ab." },
      { title: "Verbraucher koordinieren", text: "Maschinen, Gebäudetechnik und Ladepunkte benötigen klare Prioritäten. Energiemanagement muss zu Schnittstellen und betrieblichen Anforderungen passen." },
    ],
    servicesTitle: "Ein Speicherkonzept mit klarem Einsatzzweck",
    services: [
      { title: "Lastganganalyse", text: "Zeitpunkte, Höhe und Dauer des Verbrauchs sowie möglicher Spitzen auswerten." },
      { title: "PV-Abgleich", text: "Verfügbare Erzeugung, Überschüsse und Verbrauch außerhalb der Erzeugungszeiten gegenüberstellen." },
      { title: "Speicher dimensionieren", text: "Nutzbare Kapazität, Lade- und Entladeleistung sowie Betriebsstrategie zusammen auslegen." },
      { title: "Energiemanagement planen", text: "Steuerbare Verbraucher, Ladeinfrastruktur, Messung und Systemkompatibilität abstimmen." },
      { title: "Integration & Anschluss", text: "Aufstellort, Elektroverteilung und notwendige Schutz- und Anschlussmaßnahmen prüfen." },
      { title: "Betrieb auswerten", text: "Monitoring und nachvollziehbare Betriebsdaten für die spätere Bewertung des Systems vorsehen." },
    ],
    steps: [
      { title: "Daten & Ziel klären", text: "Lastgang, PV-Daten und den gewünschten Nutzen des Speichers besprechen." },
      { title: "Szenarien vergleichen", text: "Eigenverbrauch und mögliche Lastspitzenbegrenzung getrennt und in Kombination bewerten." },
      { title: "Systemkonzept erstellen", text: "Speicher, Steuerung, Aufstellort und Anschluss auf den Betrieb abstimmen." },
      { title: "Umsetzen & einregeln", text: "Anlage integrieren, Betriebsstrategie einstellen und in die Bedienung einweisen." },
    ],
    faqs: [
      { question: "Welche Daten werden für die Speicherauslegung benötigt?", answer: "Hilfreich sind ein möglichst vollständiger Jahreslastgang, Angaben zum Stromtarif und vorhandene PV-Erzeugungsdaten. Betriebszeiten, geplante Verbraucher und mögliche Einschränkungen am Standort ergänzen die Grundlage." },
      { question: "Warum sind kW und kWh beim Gewerbespeicher getrennt wichtig?", answer: "Die Kapazität in kWh beschreibt, wie viel Energie nutzbar gespeichert werden kann. Die Leistung in kW bestimmt, wie schnell der Speicher Energie aufnehmen oder abgeben kann. Beide Größen müssen zur Aufgabe im Betrieb passen." },
      { question: "Kann der Speicher Lastspitzen reduzieren?", answer: "Das kann mit einer geeigneten Auslegung und Steuerung möglich sein. Entscheidend sind Leistung und Dauer der Spitzen sowie die verfügbare Energie im Speicher. Ein wirtschaftlicher Nutzen muss zusätzlich anhand der konkreten Tarifstruktur geprüft werden." },
      { question: "Kann ein Speicher Eigenverbrauch und Lastspitzen zugleich optimieren?", answer: "Beide Ziele lassen sich unter geeigneten Bedingungen kombinieren, können aber um dieselbe Speicherkapazität konkurrieren. Deshalb werden Reserven und Steuerungsprioritäten im Betriebskonzept festgelegt und in der Auslegung berücksichtigt." },
      { question: "Kann Ladeinfrastruktur in das System eingebunden werden?", answer: "Ja, wenn die eingesetzten Komponenten geeignete Schnittstellen bieten. Wir prüfen Ladebedarf, Anschlussleistung und Prioritäten. So lässt sich bewerten, welchen Beitrag PV, Speicher und Lastmanagement jeweils leisten können." },
      { question: "Ist eine Nachrüstung an bestehender Gewerbe-PV möglich?", answer: "Das wird anhand der vorhandenen Anlage geprüft. Wechselrichter, Messkonzept, Verteilung, Netzanschluss und Aufstellbedingungen bestimmen die technische Lösung und den Umbauaufwand. Eine pauschale Kompatibilitätszusage wäre dafür nicht ausreichend." },
    ],
    formTitle: "Lassen Sie Ihren Lastgang auf Speicherpotenzial prüfen.",
    formIntro: "Beschreiben Sie Ihr Ziel und ob bereits eine PV-Anlage besteht. Die benötigten Lastgang- und Anlagendaten stimmen wir im Gespräch ab.",
    projectType: "Gewerbe-PV mit Speicher",
    qualifier: { label: "Welches Ziel hat Ihr Speicherprojekt?", options: ["Mehr PV-Strom selbst nutzen", "Lastspitzen untersuchen", "Ladeinfrastruktur einbinden", "Mehrere Ziele kombinieren", "Einsatzmöglichkeiten zunächst prüfen"] },
    related: ["photovoltaik-gewerbe", "gewerbe-pv-wirtschaftlichkeit", "photovoltaik-hallendach-industrie"],
  },
  {
    slug: "gewerbe-pv-wirtschaftlichkeit",
    category: "gewerbe",
    adGroup: "Kosten & Wirtschaftlichkeit",
    intent: "Investitionskosten, Eigenverbrauch, Amortisation und Wirtschaftlichkeit einer gewerblichen PV-Anlage projektbezogen bewerten.",
    title: "Gewerbe-PV: Kosten & Wirtschaftlichkeit prüfen | ALAB",
    description: "Was kostet Gewerbe-PV und wann rechnet sie sich? ALAB bewertet Investition, Lastgang, Eigenverbrauch und Betriebskosten für Ihr konkretes Anlagenkonzept.",
    eyebrow: "Gewerbe-PV als Grundlage für Ihre Investitionsentscheidung",
    h1: "Was kostet eine gewerbliche PV-Anlage – und wann rechnet sie sich?",
    intro: "Die Wirtschaftlichkeit wird projektbezogen aus Verbrauch, Lastgang, Dachfläche und Anlagenkonzept berechnet. ALAB macht Investition, laufende Kosten und Annahmen nachvollziehbar – damit Sie Varianten fundiert vergleichen können.",
    cta: "Wirtschaftlichkeit berechnen lassen",
    benefits: ["Projektbezogene Investitionsbetrachtung", "Eigenverbrauch aus Lastprofil bewerten", "Transparente Annahmen und Varianten"],
    heroImage: "/optimized/gewerbedach-pv-286c2c447c.webp",
    heroAlt: "Photovoltaikanlage auf dem Flachdach einer Gewerbehalle – Projekt von ALAB Energiesysteme",
    heroCaption: "ALAB-Projekteinblick: Photovoltaik auf einem Gewerbedach",
    focusTitle: "Drei Größen entscheiden über die Rechnung.",
    focusIntro: "Ein Preis je kWp beschreibt nur einen Teil des Projekts. Für eine Entscheidung betrachten wir die gesamte Investition, den nutzbaren Ertrag und den laufenden Betrieb.",
    focusItems: [
      { title: "Investition vollständig erfassen", text: "Anlagenleistung, Dachart, Montageaufwand, Elektroverteilung und Netzanschluss beeinflussen die Kosten. Notwendige Zusatzarbeiten gehören in dieselbe Betrachtung." },
      { title: "Nutzen realistisch berechnen", text: "Lastgang und Erzeugung bestimmen den Eigenverbrauch. Vermiedener Strombezug und mögliche Erlöse aus Überschüssen werden mit klar benannten Annahmen bewertet." },
      { title: "Betrieb & Finanzierung einbeziehen", text: "Wartung, Monitoring, mögliche Ersatzinvestitionen und Finanzierung verändern den Verlauf. Wir vergleichen Varianten über einen festgelegten Betrachtungszeitraum." },
    ],
    servicesTitle: "Diese Faktoren fließen in die Berechnung ein",
    services: [
      { title: "Anlagenleistung & Dach", text: "Nutzbare Fläche, Dachart und Montagekonzept als Grundlage des technischen Umfangs." },
      { title: "Netzanschluss & Elektrik", text: "Vorhandene Infrastruktur sowie notwendige Anschluss- und Verteilungsarbeiten berücksichtigen." },
      { title: "Erzeugung & Eigenverbrauch", text: "PV-Erzeugungsprofil mit Ihrem betrieblichen Lastgang abgleichen." },
      { title: "Strompreis & Überschüsse", text: "Tarifabhängig vermeidbare Bezugskosten und angenommene Einspeiseerlöse nachvollziehbar ansetzen." },
      { title: "Laufende Kosten", text: "Wartung, Monitoring und weitere projektrelevante Betriebskosten erfassen." },
      { title: "Szenarien & Kennzahlen", text: "Amortisation, Renditekennzahlen und gegebenenfalls Finanzierung unter offengelegten Annahmen vergleichen." },
    ],
    steps: [
      { title: "Datengrundlage erfassen", text: "Dach, Verbrauch, Lastgang, Stromtarif und Investitionsrahmen zusammentragen." },
      { title: "Technik konkretisieren", text: "Anlagenvarianten und den notwendigen Anschlussaufwand eingrenzen." },
      { title: "Wirtschaftlichkeit berechnen", text: "Kosten, Eigenverbrauch, Überschüsse und Betrieb mit nachvollziehbaren Annahmen bewerten." },
      { title: "Varianten besprechen", text: "Ergebnisse und empfindliche Einflussgrößen gemeinsam prüfen, bevor Sie entscheiden." },
    ],
    faqs: [
      { question: "Was kostet eine gewerbliche Photovoltaikanlage?", answer: "Das hängt von Anlagenleistung, Dachaufbau, Montage, Elektroinstallation und Netzanschluss ab. Speicher und erforderliche Zusatzarbeiten können den Umfang verändern. Den Preis nennen wir Ihnen deshalb im unverbindlichen Angebot auf Basis eines konkreten technischen Konzepts." },
      { question: "Warum reicht ein Preis pro kWp zum Vergleich nicht aus?", answer: "Angebote können unterschiedliche Leistungen und Anschlussarbeiten enthalten. Auch Erzeugungsprofil und Eigenverbrauch unterscheiden sich. Vergleichbar werden Varianten erst mit demselben Leistungsumfang und nachvollziehbaren Annahmen für Nutzung und Betrieb." },
      { question: "Wann amortisiert sich eine Gewerbe-PV-Anlage?", answer: "Der Zeitpunkt ergibt sich aus Investition, nutzbaren Erträgen und laufenden Kosten. Lastgang, Strompreis und Finanzierung beeinflussen die Rechnung. Wir nennen deshalb keine pauschale Jahreszahl, sondern bewerten das konkrete Projekt." },
      { question: "Wie wird der Eigenverbrauch in der Rechnung ermittelt?", answer: "Die erwartete PV-Erzeugung wird zeitlich mit dem Lastgang Ihres Betriebs abgeglichen. So lässt sich abschätzen, welcher Strom direkt genutzt wird und welche Überschüsse verbleiben. Die Qualität der Eingangsdaten beeinflusst die Aussagekraft." },
      { question: "Wie werden Strompreise und Finanzierung berücksichtigt?", answer: "Für die Analyse werden klar benannte Preis- und Finanzierungsannahmen verwendet. Unterschiedliche Szenarien zeigen, wie sich Änderungen auf die Ergebnisse auswirken. Konkrete Finanzierungskonditionen müssen mit Ihrem Finanzierungspartner geklärt werden." },
      { question: "Kann eine Anlage ohne Speicher wirtschaftlicher sein?", answer: "Ja, das ist je nach Lastprofil und Investitionskosten möglich. Ein Speicher erzeugt zusätzlichen Nutzen nur in passenden Betriebssituationen und verursacht eigene Kosten. Deshalb sollten Anlagen mit und ohne Speicher getrennt bewertet werden." },
    ],
    formTitle: "Schaffen Sie eine klare Grundlage für Ihre Entscheidung.",
    formIntro: "Nennen Sie uns Ihren Standort und den Stand Ihrer Planung. Wir klären die Datengrundlage und den Umfang einer projektbezogenen Wirtschaftlichkeitsanalyse.",
    projectType: "Wirtschaftlichkeitsanalyse Gewerbe-PV",
    qualifier: { label: "Wo stehen Sie mit Ihrem Projekt?", options: ["Erste Potenzialprüfung", "Investition vorbereiten", "Anlagenvarianten vergleichen", "PV mit und ohne Speicher bewerten", "Bestehende Anlage erweitern"] },
    related: ["photovoltaik-gewerbe", "photovoltaik-hallendach-industrie", "gewerbe-pv-speicher"],
  },
];
