export type LandingPage = {
  slug: string;
  category: "waermepumpe" | "photovoltaik" | "gewerbe" | "elektro";
  adGroup: string;
  intent: string;
  title: string;
  description: string;
  eyebrow: string;
  h1: string;
  intro: string;
  cta: string;
  benefits: [string, string, string];
  heroImage: string;
  heroAlt: string;
  heroCaption: string;
  focusTitle: string;
  focusIntro: string;
  focusItems: { title: string; text: string }[];
  servicesTitle: string;
  services: { title: string; text: string }[];
  steps: { title: string; text: string }[];
  faqs: { question: string; answer: string }[];
  formTitle: string;
  formIntro: string;
  projectType: string;
  qualifier: { label: string; options: string[] };
  earlyForm?: boolean;
  solarCalculator?: boolean;
  sources?: { title: string; url: string }[];
  related: string[];
};
